### ISSUE TITLE
AMAZON DOESNT KNOW WHAT IS WRONG

### ISSUE THREAD

**Issue by scargill** [datech/node-red-contrib-amazon-echo#100]
##### SUMMARY
The problem is that the software is working perfectly - turning MQTT devices on and off in respons to "Alexa turn livingroom lights on" - and "Turn living room lights off" - HOWEVER despite rebooting the Raspbryy Pi running Node-Red to ensure no cache or other issue, when I tell Amazon to do the above actions - after it has done so successfully - the Echo says "I'm not quite sure what went wrong". It does this every time. 

##### ECHO DEVICES
Echo Dot 3rd generation
-->

##### MODULE VERSION

0.1.9

```

##### CONFIGURATION
<!--- Paste export of the Node-RED flow between quotes -->
```paste below

```

##### CONSOLE OUTPUT

```paste below

```

##### STEPS TO REPRODUCE
Amazon Echo Hub feeds Amazon Echo Device node called "livingroom lights" - which sends out the message to two real devices bia timers (acts as manual override - works a treat)

##### EXPECTED RESULTS
Lights should turn on and off and Alexa should say OK.

##### ACTUAL RESULTS
Lights turn on and off but Alexa says "I'm not sure what went wrong"

**Comment by Barabba11** [comment]
Please don't argue with the author of this module for the Amazon problems.. you need simply to reset your echo device.
To do that remove it from Amazon account, reset it to factory pressing buttons (see in YouTube how for your device), associate again to account and discover again devices.
Do this and don't touch nothing on Raspberry, you will see where is the problem

**Comment by scargill** [comment]
Hi

I'm not arguing with anyone - I am grateful for this software. However I just factory reset the Echo dot after deregistering it... re-registered and now told it to find devices... making sure that the relevant (Tasmota) devices (living room one and living room two)  are not using emulations. Once again the same - using the node "living room lights" the output to MQTT from the device node is working - Alexa can turn on and off the node in response to verbal requests - yet the message continues "I'm not sure what went wrong". Other REAL (Tasmota) devices respond perfectly,.

**Comment by datech** [comment]
Hello @scargill,

I've documented a similar error in the [Troubleshooting](https://github.com/datech/node-red-contrib-amazon-echo/wiki/Troubleshooting) page, but I'm not sure it is the same problem in your case.

> Alexa: "I am not quite sure what went wrong"
> Check that your Node-Red instance is not running on multiple network interfaces from the same network. For example, your Node-Red may be listening on ethernet and WiFi interfaces.

**Comment by datech** [comment]
@scargill, have you managed to find how to resolve it?

**Comment by scargill** [comment]
Thanks for that and sorry for not putting the solution to my problem back in here. In fact, despite my best efforts, the PI was running a WIFI HHCP connection as WELL as my wired static address. By finally getting rid of the pesky DHCP, the node now works correctly (which is more than can be said for Alexa.  Amzzon should be more specific about words they reserve... using anything with "lights" in it seems to be asking for trouble. Howwever, the point is, the n-r-c-amazon-echo node is working perfectly, thanks.

**Comment by datech** [comment]
Thanks for the feedback.
