### ISSUE TITLE
Doesn't output %, on/off works

### ISSUE THREAD

**Issue by raufis27** [datech/node-red-contrib-amazon-echo#102]
##### SUMMARY
% doesn't work. Only ON of OFF command output.

##### ECHO DEVICES

* Echo Dot 1st generation
* Echo Plus 2nd generation 

##### MODULE VERSION

0.1.10

```

##### CONFIGURATION
<!--- Paste export of the Node-RED flow between quotes -->
```paste below

```

##### CONSOLE OUTPUT

```
msg.payload : string[2]
"on"
```

##### STEPS TO REPRODUCE
Alexa, set {device} to 50%

##### EXPECTED RESULTS
msg.payload : string[2]
"50"

##### ACTUAL RESULTS
msg.payload : string[2]
"on"

**Comment by datech** [comment]
It is expected behavior.

Result on "set {device} to 50%"  command will be:
```
msg: {
   "payload":"on",
   "on":true,
   "bri":128,
   "percentage":50,
 ...
 ...
 }
```

**Comment by raufis27** [comment]
Sorry, I don't get it. If I ask Alexa, or use Alexa app to change brightness, I get only on/off command. Ho do I get percentage of brightness ?

**Comment by datech** [comment]
The payload attribute of the msg is either on or off. Bri and percentage are attributes on the msg, not on the payload. Are you checking the full message or just the payload?

**Comment by raufis27** [comment]
I have debug node connected to output of hub and "device".

**Comment by raufis27** [comment]
I see what do you mean now.

**Comment by datech** [comment]
Feel free to reopen if you find any inconsistency with the documentation

**Comment by raufis27** [comment]
Could you please share example of parsing percentage value from entire message ?
