### ISSUE TITLE
Echo Dot responds with "I don't know what went wrong" when trying to control device, although flow works flawless

### ISSUE THREAD

**Issue by TheLongAndOnly** [datech/node-red-contrib-amazon-echo#103]
##### SUMMARY
I created a flow to allow turning my Yamaha amplifier on/off through Alexa:

I'm using iptables to get around the port 80 / admin issue:
`*filter
:INPUT ACCEPT [19503:5794156]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [16918:3841349]
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 10080
-A PREROUTING -p udp -m udp --dport 80 -j REDIRECT --to-ports 10080
COMMIT`

##### MODULE VERSION

```paste below
node-red-contrib-amazon-echo 0.1.9
```

##### CONFIGURATION

```paste below
[{"id":"dc4ad69.3be90a8","type":"amazon-echo-hub","z":"85a56912.9744","port":"10080","processinput":0,"x":110,"y":160,"wires":[["56c24782.5ab5a8"]]},{"id":"56c24782.5ab5a8","type":"amazon-echo-device","z":"85a56912.9744","name":"Yamaha","topic":"","x":300,"y":160,"wires":[["bada4520.6cfb3"]]}]
```
(only the relevant part is pasted)

##### CONSOLE OUTPUT

```paste below
No entries in node-red-log during execution
```

##### STEPS TO REPRODUCE

* Set up flow
* Call Alexa turn on Yamaha

##### EXPECTED RESULTS

* Flow should deliver the "on" command
* Alexa should return or positive response

##### ACTUAL RESULTS

* Flow delivers the expected "on" command 
* Alexa tells me: "I don't know what went wrong"

**Comment by datech** [comment]
Looks similar to #100

**Comment by datech** [comment]
@TheLongAndOnly Have you checked the network interfaces and restart of the Echo devices?

[Troubleshooting page](../wiki/Troubleshooting)

#### Alexa: "I am not quite sure what went wrong"
* Check that your Node-Red instance is not running on multiple network interfaces from the same network.
For example, your Node-Red may be listening on ethernet and WiFi interfaces. [Issue #77](../issues/77)
* Restart your Alexa devices. [Issue #81](../issues/81)
