### ISSUE TITLE
"Alex, Dim Family Room lights to 50%" sends 2 commands

### ISSUE THREAD

**Issue by InstigatorX** [datech/node-red-contrib-amazon-echo#105]
2 messages are sent when saying "dim family room lights to 50%". First one is the original brightness and second one is the 50% brightness. This has the effect of lights on at previous brightness and then dimming down from that. If previous brightness was 100% its super bright for a moment and then 50%.

**Comment by datech** [comment]
Yep, it’s expected behavior as Alexa is sending two different command for “on” and bri change.

The following issue might give you more details: https://github.com/datech/node-red-contrib-amazon-echo/issues/71#issuecomment-539626497

**Comment by InstigatorX** [comment]
Thx. Will give it a try, but don’t you think this is more of a workaround than an actual fix?

**Comment by Barabba11** [comment]
How we can fix Alexa behaviour?

**Comment by InstigatorX** [comment]
Maybe build some logic in that detects this use case and only sends the 2nd request?

**Comment by datech** [comment]
We've discussed this in the past, so it looks like it is better not to change the default Alexa behavior. It is possible to implement any logic in your flow. That's why I see it more like a workaround if we imbed any logic in the hub.

**Comment by Barabba11** [comment]
I agree, I strongly suggest to add a function, or better use the author flow suggestion, to filter out the unnecessary message. This means less probability of bugs/issues in the module for all other users. Search in closed topics for that example
