### ISSUE TITLE
Option to issue an MQTT message when a device is set to X%

### ISSUE THREAD

**Issue by DonnyBahama** [datech/node-red-contrib-amazon-echo#112]
**Describe the solution you'd like**
I’d like to be able to send one of many MQTT messages based on the percentage I specify in the command. If I say, “Alexa, set {device} to 17%”, then MQTT_msg_17 is sent. When MQTT_msg_17 is received, any number of actions could then be triggered. Using an Alexa routine, I could then use a descriptive trigger phrase to do what I want by executing the “set device to X%” command, resulting in locally executed commands with almost unlimited flexibility.

**Describe alternatives you've considered**
I believe I’ve looked at every conceivable way of sending a variety of MQTT messages via Alexa commands - both locally or with cloud usage.

**Comment by datech** [comment]
I'm not sure this is a malfunction or feature request related to this module, but you can always use "mqtt out" node multiple times after each device.
