### ISSUE TITLE
Alexa colors does not match

### ISSUE THREAD

**Issue by DcFamas** [datech/node-red-contrib-amazon-echo#114]
##### SUMMARY

Hey there,
the colors does not match with the output in node red.
For example when I say "Alexa turn the light white" the output is
`[254,0,0] `

The light turns red.

When I say "Alexa turn the light red" the output is still red and `[254,0,0]`

##### ECHO DEVICES
Echo Dot 2nd gen.
Echo Dot 3rd gen.
Echo Plus 2nd gen.

##### MODULE VERSION

```
0.1.10
```

##### CONFIGURATION
```
[
    {
        "id": "91adab88.2e347",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "2498a9a9.581f86",
        "type": "amazon-echo-device",
        "z": "91adab88.2e347",
        "name": "light",
        "topic": "",
        "x": 550,
        "y": 380,
        "wires": [
            [
                "c5d1b171.4a11a8"
            ]
        ]
    },
    {
        "id": "556ec63a.4d4228",
        "type": "debug",
        "z": "91adab88.2e347",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": true,
        "tostatus": true,
        "complete": "rgb",
        "targetType": "msg",
        "x": 870,
        "y": 380,
        "wires": []
    },
    {
        "id": "c5d1b171.4a11a8",
        "type": "change",
        "z": "91adab88.2e347",
        "name": "msg.rgb",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "rgb",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 700,
        "y": 380,
        "wires": [
            [
                "556ec63a.4d4228"
            ]
        ]
    },
    {
        "id": "1d455393.381b2c",
        "type": "amazon-echo-hub",
        "z": "91adab88.2e347",
        "port": "80",
        "processinput": 0,
        "discovery": true,
        "x": 370,
        "y": 380,
        "wires": [
            [
                "2498a9a9.581f86"
            ]
        ]
    }
]
```

##### CONSOLE OUTPUT
```
11.4.2020, 14:44:35node:
msg.rgb : array[3]
array[3]
0: 254
1: 0
2: 0
```

**Comment by Alacritous** [comment]
Most LED's have 3 colors and a white LED. so when you set the color to white it just assumes you want the white LED on.  What it won't do is send 255,255,255 as the color white.  You'll have to do some checking on the color mode and use node-red to figure out if it's white you want or a color setting. 

It's how the system treats the lights. It thinks lights are a Phillips smart bulb. 

I sent 2 commands. One to set the light to "WHITE" and one to set the light to "BLUE" 

You can see the entire msg object for each below.  You'll have to extract the data you want from the msg object and tell NR what to do with that info. 

![image](https://user-images.githubusercontent.com/1443724/102737839-b4136700-4305-11eb-9228-2766f16fd472.png)

**Comment by Alacritous** [comment]
Just playing more. and it looks like there are two modes. CT mode is for temperatures of white. and HS mode is color mode.  It uses various values to display colors. like what appears to be the x,y coordinates on a color wheel for color selection as well as hue and saturation levels. This is nothing to do with this Node-red plugin. These are values being provided by the Alexa system because it thinks it's talking to a smart lightbulb.
