### ISSUE TITLE
Get device ID of calling echo

### ISSUE THREAD

**Issue by jasonkelly214** [datech/node-red-contrib-amazon-echo#116]
Am I missing it or is there a way to get the device ID of the echo making the request? I used three different devices but see the same IP in the debug message. Are all messages being passed from a single echo? The IP listed is gen 2, all other devices are gen 1. However when I use the alexa app on my phone the same IP shows up.

**Comment by datech** [comment]
Duplicate to #59

**Comment by Barabba11** [comment]
If you want to see 3 IP use 3 different Alexa accounts
