### ISSUE TITLE
Devices discovered double 

### ISSUE THREAD

**Issue by YanivYon** [datech/node-red-contrib-amazon-echo#117]
Hi
all my Lights that i programmed are being discovered twice
once as "Royal Philips Electronics" and once again as "Hue Light"
in the Alexa settings on all the "Royal Philips Electronics" devices show as connected via one of my Echo Dots
and the other ones are connected via "Hue Hub"
how can i prevent this?
every rediscovery i have to delete all the double items

**Comment by datech** [comment]
Have you tried to start the discovery procedure with a single Echo device? Just switch off all Echo devices except one.

**Comment by YanivYon** [comment]
No i haven't tried it like this
Put that's not an acceptable solution, even if it would work.
Disconnecting 4 echos and leaving just 1 plugged it es even more complicated then removing the double devices
I tried discovery from my phone and from amazon website

**Comment by datech** [comment]
I'm not saying this as a solution. I have 3 Echos, and all devices are discovered just once. Usually, there is one master Echo device which is responsible for the discovery requests. I suppose that for any reason, you have two master Echos. I don't know why, how, and when we could have multiple master Echos.  So, what was the result with one Echo?

**Comment by Barabba11** [comment]
Are you using the same account for all devices? Seams yes. You may eventually try to register each echo on a different account (create them). it looks a bug of Amazon, different echoes with different firmwares work/discover in a different way, there may be needed to update all their firmwares.
You may also try to discover devices to the master only, and with vocal command only, the others will already know all devices as have the same account.
You may also want to sniff IP packets when double devices are discovered and post here them

**Comment by datech** [comment]
@YanivYon, did managed to test it? Any update?

**Comment by djryan012** [comment]
I am also having similiar issues. tho a side note in addition. I remove all devices and do a rediscover. Alexa is discoving some of the devices with old names and some that were deleted from node red flow. I only have two echos dots and are both running software v. 653621620.

**Comment by sarsw** [comment]
Hi, I've had this problem for sometime.  My "TV" switch appears as a "Royal Philips Electronics smart device" twice when I perform a search for devices in the UK Alexa online web interface. I can delete one but 2 come back at the next search.  Others switches dup up too. I find the web interface more reliable at finding new devices rather than initiating a search at either my first gen or another Alexa device in the house. I'm running version 0.1.10 on NR v0.20.8.  I have various access points on my home LAN, but all using the same subnet and the one router to the internet.

**Comment by Asengi** [comment]
I had the same issue but managed to get rid of the ghost devices eventually. The solution in my case was to first stop node red and remove the devices using the Amazon Alexa web page. Then I unplugged all my echos save one and ran a device discovery. I repeated the discovery for each echo with the others unplugged. Finally I plugged in all echos again, started node red and did a new device discovery, finding only the correct devices.

**Comment by EspElement** [comment]
I have the exact same issue. I have ruled out every possible issue. It seems to be remembering old devices. I changed the name of something months ago and now it keeps showing up. Not sure why. It's pretty irritating that's for sure. Lol

**Comment by EspElement** [comment]
> I had the same issue but managed to get rid of the ghost devices eventually. The solution in my case was to first stop node red and remove the devices using the Amazon Alexa web page. Then I unplugged all my echos save one and ran a device discovery. I repeated the discovery for each echo with the others unplugged. Finally I plugged in all echos again, started node red and did a new device discovery, finding only the correct devices.

I will try this now!

**Comment by EspElement** [comment]
> I had the same issue but managed to get rid of the ghost devices eventually. The solution in my case was to first stop node red and remove the devices using the Amazon Alexa web page. Then I unplugged all my echos save one and ran a device discovery. I repeated the discovery for each echo with the others unplugged. Finally I plugged in all echos again, started node red and did a new device discovery, finding only the correct devices.

This seems to have worked. I reset 2 of my dots to get them to stop. Thank you so much. This is the solution!
