### ISSUE TITLE
Hub node as config node

### ISSUE THREAD

**Issue by jensrossbach** [datech/node-red-contrib-amazon-echo#119]
I would like to suggest a different node architecture although this will probably break existing flows. 

Currently the Amazon Echo Hub node is an ordinary flow node. This requires that you have a single/central flow where you put the hub node with all device nodes together. When you have a lot of devices and you want to connect these devices with nodes on other flows, you have to use link or mqtt nodes and this makes your setup much more complex.

The proposal is to turn the Amazon Echo Hub node into a config node (which is then not bound to a flow anymore) and let the device nodes communicate with the Amazon Echo Hub node via API calls / callbacks instead of messages over connections drawn by the user (which could also be more error-prone). Then any node which needs to interact with the Amazon controllable device can simply be connected to the input and output ports of the device nodes (instead of being connected to a device node on one side and to the hub node on the other side). Furthermore, the device nodes can easily be spread over different flows.

I know that this would be a big, breaking change but in my opinion it is worth thinking about.

**Comment by datech** [comment]
You might want to try using multiple devices spread between flows and linked with "**link in**" and "**link out**" nodes. I personally use the same approach.
