### ISSUE TITLE
Echo Plus as gateway?

### ISSUE THREAD

**Issue by Zabov79** [datech/node-red-contrib-amazon-echo#12]
My configuration: 
- Amazon Echo Plus
- 1x Philips Hue Bulb
- 1x Ikea Tradfri Bulb
- 2x Sonoff/Tasmota switch
- Raspberry Pi with MQTT and Node-Red

I do not own a Hue Bridge or a Tradfri Gateway.

The Sonoff switches work as a charm. I can control them using Alexa voice command, Alexa app, physical switches and so on.
The bulbs can be controlled via Alexa voice commands and app, since my Echo Plus integrate a Zigbee protocol to comunicate with these.
I'd like to control them using some flows in node red. For example: use a sonoff as a switch button -> mqtt message -> node red -> echo plus -> Philips Hue bulb turns on. This is what I'd like to do. Is it possibile in some way or I MUST buy a Philips Hue bridge?

**Comment by wongnam** [comment]
You can use Alexa App routines function to do this.

**Comment by Barabba11** [comment]
Yes you can do probably and without using node red. If you want node red to add infinite possibilities with functions you need to set is as hub, Alexa will tell node red what to do and node red to other devices..
You can't use Alexa as hub.. I guess

**Comment by Zabov79** [comment]
Already tried With routine but there’s no sonoff device to choose in the “when” part. remember that I flashed the sonoff with tasmota so I lost the official compatibility through the ewelink skill/app

**Comment by wongnam** [comment]
> Already tried With routine but there’s no sonoff device to choose in the “when” part. remember that I flashed the sonoff with tasmota so I lost the official compatibility through the ewelink skill/app

Yes, I just checked that Sonoff is not a support device to trigger in Alexa App.

**Comment by Barabba11** [comment]
if you can connect Sonoff to Node Red than you can use this module to drive your Sonoff by Node Red as hub

**Comment by wongnam** [comment]
May be this is off topic because @Zabov79 asking how to use **Node-Red to control Echo plus -> Philips Hue bulb turns on** .

**Comment by datech** [comment]
@Zabov79 Can you share to the DIY solution you have found before closing the issue? Thanks.

**Comment by Zabov79** [comment]
Well it consist in "building" a zigbee hub using a raspberry pi as base system with a CC2531 usb sniffer   reprogrammed. There's a guide in Italian which is based on this wiki [https://github.com/Koenkk/zigbee2mqtt](url). This should consent to use a raspberry pi with home assistant as Mqtt broker and zigbee hub at the same time, integrating the two protocols. I bought online the cc2531 and other stuff needed to flash it on aliexpress but its really really cheaper than buy a Philips Hue Bridge.

**Comment by datech** [comment]
Cool! Thanks for sharing this out.
