### ISSUE TITLE
RBGW/RBGWW light control

### ISSUE THREAD

**Issue by andymarden** [datech/node-red-contrib-amazon-echo#120]
currently, an echo device only returns RGB colours with this - it is missing the white channel. It works fine directly between Alexa and the MagicHome controllers, but when I integrate with HA, I have no value to pass to white_value in flux_led.
/
Can you add that to the message properties? Should be no issue since Alexa is clearly sending it.

**Comment by datech** [comment]
Can you give an example of what exactly Alexa is sending to the hub and is not returned in the output payload?

**Comment by andymarden** [comment]
I am seeing if I can get that - but essentially, RGBW lights have an 
extra channel/value for white. So if I have the lights on, the white is 
not controlled so that colour is wrong - eg, asking the lights to turn 
red leaves white at full brightness, so it's not correct. I imagine that 
there is an extra value being sent, which would then be passed to 
flux_led as white_value.

I have done a pull request and was going to look into it - but given I 
don't know javascript, it might be a tall order! Do you have a 
definition of the complete schema for what Alexa send out when 
communicating to Philips Hue? I can probably identify point in the right 
direction.

------ Original Message ------

**Comment by andymarden** [comment]
I believe one of the other alexa node red packages deals with it - the 
ones that need AWS. Maybe have a look there. I will see what I can find 
out.

------ Original Message ------
From: "Andy Marden" <amarden@usa.net>
To: "datech/node-red-contrib-amazon-echo" 
<reply@reply.github.com>; 
"datech/node-red-contrib-amazon-echo" 
<node-red-contrib-amazon-echo@noreply.github.com>
Cc: "Author" <author@noreply.github.com>
Sent: 23/04/2020 11:19:40
Subject: Re[2]: [datech/node-red-contrib-amazon-echo] RBGW/RBGWW light 
control (#120)

**Comment by datech** [comment]
Here you can find the Philips Hue API, which is emulated by this module. https://developers.meethue.com/develop/hue-api/

You have two modes
- "HS" for Hue and Saturation
- "CT" for Color Temperature

Mixed mode  - RGB + White is not supported, but you can easily implement it as custom logic for your specific case.

**Comment by andymarden** [comment]
Thanks - i tried various combinations but I think flux_led is broken for rgbw lights. I can get what I need, in theory, I think, by detecting hs or ct and setting various parameters. But i get strange behaviour with white-value and kelvin.

So I think you have done all you can - I'll see whether I can get something sensible worked out!

Cheers
Andy
