### ISSUE TITLE
Port 80 bereits in Benutzung und das muss so bleiben.

### ISSUE THREAD

**Issue by Gordon2Freeman** [datech/node-red-contrib-amazon-echo#122]
Moin, habe ein etwas spezielles Problem: 

Setup: RPi4 mit PivCCU + IoBroker inkl. NodeRED/Alexa + Conbee/Deconz + PiHole auf einem System. 
Im Netzwerk ist u.a. ein Echo Dot 3rd Gen. 

Der Conbee-Stick muss auf Port 80 laufen, damit der Echo Dot die Geräte findet. In node.red nutze ich "Node-red-contrib-Amazon-echo", um virtuelle Geräte für Alexa zu kreieren, ohne Cloud bzw. iobroker Cloudserver nutzen zu müssen. Dafür muss ich mich in node.red mit dem Echo Dot verbinden. 

Das geht aber nur über Port 80 und ergibt natürlich die Fehlermeldung: 
_[error] Error: listen EADDRINUSE: address already in use :::80_

Ergo: Deconz und auch das Node-RED-Modul MÜSSEN beide auf Port 80 laufen bzw. zugreifen, damit der Echo Dot alle (virtuellen) Geräte findet. Wie bekomme ich das hin? Ein Portforwarding von 2 unterschiedlichen Ports auf Port 80 geht nicht. Meine derzeitge Überlegung wäre es, dem Deconz-Service eine eigene virtuelle IP-Adresse zu geben (PivCCU und IoBroker haben auch 2 IP-Adressen auf dem gleichen Gerät), aber ich habe leider keine Ahnung wie das gehen könnte, da meine Linux Kenntnisse nicht so weit gehen. Gibt es weitere Lösungen?

**Comment by Barabba11** [comment]
we don't understand german, sorry. You probably need to kill the process that is using port 80, or better move it to another port. You need port 80 to discover devices with Alexa

**Comment by tronotoc** [comment]
Nutze eine virtuelle Maschine mit eigener IP, dort kannst Du es dann auf Port 80 legen.

**Comment by RoberTo1111** [comment]
Setz den Conbee auf einen anderen Port. Auf 80 läuft ja nur die Webmanagement GUI für DeCONZ. Im Startscript von DeCONZ --http-port=GEWUENSCHTEPORTNUMMER eintragen.

Dann noch Port 80  berechtigen mit: sudo setcap 'cap_net_bind_service=+ep' /usr/bin/node. 
CU
R.

**Comment by datech** [comment]
Thanks for submitting an issue. Unfortunately, we provide support only for issues written in English.
