### ISSUE TITLE
Differentiate between two different origins (I have more than one echo DOT)

### ISSUE THREAD

**Issue by miguc** [datech/node-red-contrib-amazon-echo#124]
I have two echo dot and I want to differentiate from where I launch the command, to respond with a specific message to the echo who is the origin of the command.

Apparently, meta.insert.by.details suggests it could be differentiated, but it doesn't.

Could this origin identification be generated?

**Comment by datech** [comment]
Duplicate to #59

**Comment by miguc** [comment]
Sorry.  Isaw it.
