### ISSUE TITLE
EchoDot3 only sends "on"/"off" Payloads to Node-Red-Hub

### ISSUE THREAD

**Issue by GLauer0815** [datech/node-red-contrib-amazon-echo#126]
Hi,
i connected a flow successfully to ED3 and i can turn the correspondig Lamp on/off via Alexa.
But Dimming or coulor-changing commands via Alexa are generating only "on" payloads.
Has anybody an idea what´s going wrong?

**Comment by Barabba11** [comment]
Check the meta object, it contains useful informations

**Comment by GLauer0815** [comment]
@Barabba11 :
Ty so much:
I left my debug node output to "msg.payload". After changing to full msg object i can see the whole msg from Alexa :)
