### ISSUE TITLE
New Alexa vocal algorithm, different commands and behaviours

### ISSUE THREAD

**Issue by Barabba11** [datech/node-red-contrib-amazon-echo#127]
Hi, recently I discovered new behaviours, Alexa (in Italian language) doesn't support more shutter's command "open", as in Italian similar to "switch on", it became now more specific and say this object (light, as emulated with this module) doesn't support that function. So I need a shutter device, if I don't want to "switch on" the curtains xD, there can be any idea about it?

Another issue: I've created a device "all" to make me to certain actions when I say "Alexa switch off all", but she understands herself all as an action and turn off everything, including curtains. Any way to overcome it? Thanks

**Comment by Barabba11** [comment]
There is any way to force on the Alexa app a light to become a shutter? 

For the turn all off I may have this idea, I can filter out all messages from Alexa and delay them a couple of seconds, I can create a special device with a useless name and if there is a m  essage incoming about it I'll reset the last message (on delay node) and execute it, if nothing is coming it will be passed the last command

**Comment by datech** [comment]
This module will support only lights. You may use Alexa routines to simulate different types of devices and commands. To support a broader range of devices, an Alexa Skill will be needed. More information can be found in issue #196.
