### ISSUE TITLE
Amazon Echo Hub Offline after Update to Node 12.18.0

### ISSUE THREAD

**Issue by Atredis76** [datech/node-red-contrib-amazon-echo#128]
I´m using Node Red under IOBroker.
When I make an Update to Node 12.18.0 the Amazon Echo Hub is Offline.
In the same settings under 12.17.0 The Device is Online and works fine.
The Node-Red Adapter under IOBroker is 1.17.2

**Comment by datech** [comment]
I cannot reproduce this issue with node-red-contrib-amazon-echo v0.1.11, Node-RED 3.1.18, and Node.js v16.20.2.
