### ISSUE TITLE
Umlauts not properly formatted?

### ISSUE THREAD

**Issue by cg089** [datech/node-red-contrib-amazon-echo#129]
Hi,

running latest version which runs just fine.
However, if I name something with german umlauts (ä, ö, ü), they seem to be misformatted.

For example, I have a switch called "Küche" (kitchen). Alexa does not understand "Küche", and asks whether I ment K¼c-ha (spelling "one fourth").

I know similar problem with umlauts, when they are e.g. saved as UTF-8 but regarded as ISO 8859-1

**Comment by brisk4github** [comment]
Du kannst in der Alexa-App anschließend den Namen ändern.

**Comment by datech** [comment]
Duplicate to #74
