### ISSUE TITLE
Root user?

### ISSUE THREAD

**Issue by scargill** [datech/node-red-contrib-amazon-echo#13]
Does NR HAVE to be run as root user? The guys at IBM have always suggested NOT doing that - I run NR as PI user. And if that is possible - is there a way to change port 80, as I already have a webserver running on port 80?? Sounds more like a feature-erquest/query than an issue.

**Comment by datech** [comment]
Hello, 

Yes, you can change the port. Just go and edit Amazon Echo Hub node settings to set any port you want. Bear in mind that all new Echo devices will try to connect to port 80 even if different port is configured. It is not necessary to use root user, but it is the easiest way to run a process that can utilize ports under 1024.

https://github.com/datech/node-red-contrib-amazon-echo/wiki/Troubleshooting

**Comment by scargill** [comment]
Right, working as Pi - port 8980 - didn't understand the port forwarding - but it is working on port 8980 thanks. What can you send to the input if enabled?

**Comment by datech** [comment]
You might find all input params in Amazon Echo Hub node help.

Click on the node -> **info** tab -> **Node help** section

**Comment by scargill** [comment]
I didn't. I found the help section generally tells you what the payload output means. On input I noted payload output colormode was "hs" so I tried changing it so that it would say "RGB" I used an inject with a string, value "rgb"  - followed by a function to copy msg.payload to msg.payload.colormode. Did nothing. Then I triedinjecting json - {"colormode":"rgb"} - no errors but no change.

**Comment by datech** [comment]
Color mode cannot be set with input params. It will be automatically selected based on ct, hue and sat settings.

Here is an example of input message to Amazon Echo Hub node:
```
{
  "on": true,
  "bri": 51,
  "ct": 153
}
```
Note: Payload is JSON

and here is the doc of Amazon Echo Hub node: 

<h3>Inputs</h3>
  Enable input to allow input payload signals
  <dl class="message-properties">
      <dt>payload
          <span class="property-type">string | buffer</span>
      </dt>
      <dd> the payload of the message to publish</dd>
      <dt>payload.nodeid <span class="property-type">string</span></dt>
      <dd>Node ID is Amazon Echo Device Node ID</dd>
     <dt>payload.on <span class="property-type">string</span></dt>
     <dd>on/off state of the light</dd>
     <dt>payload.bri <span class="property-type">number</span></dt>
     <dd>Brightness of the light (min 1, max 254)</dd>
     <dt>payload.hue <span class="property-type">number</span></dt>
     <dd>Hue of the light (min 0, max 65535)</dd>
     <dt>payload.sat <span class="property-type">number</span></dt>
     <dd>Saturation of the light (min 0, max 65535)</dd>
     <dt>payload.ct <span class="property-type">string</span></dt>
     <dd>The mired color temperature of the light (min 153, max 500)</dd>
  </dl>

**Comment by datech** [comment]
The missing bit in the example above is nodeid attribute. It is mandatory as it tells to the hub which device will be controlled. 

```
{
    "on": false,
    "bri": 100,
    "ct": 199,
    "nodeid": "2cab1155.198e3a"
}
```

Note: In order to have an output message at least one of the attributes must change its previous value. This is done to prevent infinite loops.

**Comment by scargill** [comment]
That worked - thank you. I'll make a note so I don't forgwt - obvious really that it would need to know which device...

**Comment by scargill** [comment]
Sorry to be thick - one more example please? This doesnt work..
{   "on": true,  "rgb":[244,0,0], "nodeid":"ded8290da64588"  }

**Comment by datech** [comment]
Only those listed in the input section are currently supported

**Comment by scargill** [comment]
Yes, it is all clear now - magic - thanks - I will keep up with progress, this is an inportant pair of nodes.
