### ISSUE TITLE
Device is unresponsive

### ISSUE THREAD

**Issue by EspElement** [datech/node-red-contrib-amazon-echo#130]
All custom devices are now all the sudden unresponsive. I suspect Echos had an update? I do not see anything new in HA or Node Red to indicate update needs.

I have tried many things in my network, and all points to loss of the Node Red function of the custom commands. Example, my hue lights still work.

I have Echo Gen 2 and two Echo Gen 3 Dots. I am running HA thru Docker and Node Red add on, so I should be free to pull anything as needed, just need the commands.

Thanks!
Joshua

**Comment by Barabba11** [comment]
Did you restored a backup recently? When you do that the devices will have a new ID, so the old ID Alexa learned become unresponsive.
Try to search for new devices. Or, delete all, unassociate device from your account and reset Echo, search again. Be sure that the device discovery is enabled in hub, default is disabled.

**Comment by EspElement** [comment]
Yes and no, I have restored a backup but it worked fine then. Here is what I have tried now.

Tried removing all from Alexa App and readd, not getting the connection when discovering devices.
Tried using iptables to change port to 8080 to see if that works (in node red, it says the hub is connected with or without doing this, so not sure what the deal is).
Tried adding a new device node with a brand new name with no dice.
I have discovery checked, and right now it is set to process (not sure what the differences are in the selections process, process output, process output on state change).

Something ODD. I changed it to a no name port and it says it is online... I cannot see this being possible? Maybe that is my issue?

**Comment by EspElement** [comment]
So after an install of HassOS and restoring a backup, I tried to put a new one in, and what do you know, it worked! Thanks guys

Cheers
Joshua

**Comment by Barabba11** [comment]
Since the author will not introduce the unique ID for devices never restore any backup, our you will have your device unresponsive. You better copy the flow files and restore them manually

**Comment by EspElement** [comment]
Had to replace nodes with new ones and new names for Alexa to detect new device. Thank you!
