### ISSUE TITLE
General question: start with node red a Action on echo.dot

### ISSUE THREAD

**Issue by get-command** [datech/node-red-contrib-amazon-echo#134]
Hi community,

It is possible to start e.g. a selected Song or 'my news' or own skill or hear mode (like i say 'alexa' to trigger) on echo with a node?? 

I Use these Nodes and its function very well and very smart but only to controll Smart home devices... 

Thanks for advance!

**Comment by Barabba11** [comment]
To use skills you need different module, this module is made to work without internet too, skills need internet always.
You can use this module and drive a local music in your hifi, using appropriate modules, by say Alexa switch on mytrackname.
Don't use generic names such music for nodes, you confuse Alexa

**Comment by get-command** [comment]
Hi,

thank you for Information!

Have a nice day.
