### ISSUE TITLE
meta.insert.details.ip is always the same ip not matter what echo device I use

### ISSUE THREAD

**Issue by ericvitale** [datech/node-red-contrib-amazon-echo#135]
##### SUMMARY

The value in meta.insert.details.ip is always the same ip not matter what echo device I use. I wasn't sure if it should be the ip address of the echo I am saying the command to, but I saw this post in another issue that says it should be.

https://github.com/datech/node-red-contrib-amazon-echo/issues/69#issuecomment-539674081

##### ECHO DEVICES

Echo 1st Generation
Echo Dot 1st Generation
Echo Dot 2nd Generation

##### MODULE VERSION

```paste below
0.1.10
```

##### CONFIGURATION

```paste below
[{"id":"28212899.2e14b","type":"tab","label":"Alexa Shortcuts","disabled":false,"info":""},{"id":"ef61c6be.b450f8","type":"amazon-echo-hub","z":"28212899.2e14b","port":"80","processinput":"2","discovery":true,"x":410,"y":920,"wires":[["ea5bd41.4323128"]]},{"id":"ea5bd41.4323128","type":"amazon-echo-device","z":"28212899.2e14b","name":"Fan","topic":"","x":520,"y":840,"wires":[["31db8d4a.e9b25a"]]},{"id":"31db8d4a.e9b25a","type":"debug","z":"28212899.2e14b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":660,"y":900,"wires":[]}]
```

##### CONSOLE OUTPUT

```paste below
{"on":true,"bri":254,"percentage":100,"hue":0,"sat":254,"xy":[0.6484272236872118,0.33085610147277794],"ct":199,"rgb":[254,0,0],"colormode":"ct","meta":{"insert":{"by":"alexa","details":{"ip":"::ffff:10.55.1.166","date":"2020-07-06T18:37:40.145Z"}},"input":{"on":true},"changes":{}},"payload":"on","deviceid":"ea5bd414323128","topic":"","_msgid":"ae70930e.1e27d"}
```

##### STEPS TO REPRODUCE

Say command to echo using different echo devices, gets the same ip address.

##### EXPECTED RESULTS

I expected the ip field to have the ip address of the echo device I said the command to.

##### ACTUAL RESULTS

Same IP address, no matter what device I use.

**Comment by Barabba11** [comment]
Already discussed different times, use different Amazon accounts, on for each echo, and you will see different IP

**Comment by ericvitale** [comment]
Sorry. I didn't see this in any of the documentation.

**Comment by Barabba11** [comment]
Have a look on topics on the closed discussions.

Maybe Datech could put this common issue in Wiki throubleshoot too.
