### ISSUE TITLE
making state visible to echo device

### ISSUE THREAD

**Issue by aseedorf** [datech/node-red-contrib-amazon-echo#138]
I can switch a device by node-red with this node and also with alexa (echo dot, mobile...).
But the state-change if done with the node is not visible with e.b. my mobile.
the mobile thinks, the "old" state of the device is the actual state.
the amazon echo hub has the ability to use a state as input, but how do i get it to the correct device?
so, how do i have to build up the msg.payload to get the state to the device via amazon alexa hub?

**Comment by datech** [comment]
Check the following wiki: https://github.com/datech/node-red-contrib-amazon-echo/wiki/Integration-with-Sonoff-Tasmota

Also you may want to check the **Node help** of **Alexa Echo Hub node** as reference to the supported attributes.
Don't forget the change the **Process input** setting as by default the hub will ignore the input

**Comment by fmuntean** [comment]
I have the same issue:
I am passing the msg.payload as described but the status is not changed on Alexa App.
Is there something I am missing?
I am passing the deviceid, on, and bri variables inside the payload.
I also set the Process input to Process

**Comment by aqWCfFgvp81SqO** [comment]
Same here.  It was working (last I checked was a few months ago), but now it is not.  Still troubleshooting through it.  Seems as though all input is ignored.

**Comment by I3imbel** [comment]
I had the same issue yesterday. The problem was, that I was not able to enable the process input.
So I exported the Amazon Echo Hub knot, edited the processinput from 0 to 1 in a text editor and imported it back.
After a Node Red restart it worked just fine.

**Comment by aqWCfFgvp81SqO** [comment]
> I had the same issue yesterday. The problem was, that I was not able to enable the process input.
> So I exported the Amazon Echo Hub knot, edited the processinput from 0 to 1 in a text editor and imported it back.
> After a Node Red restart it worked just fine.

Amazon Echo Hub *knot* ??

Did you intend to type node?

**Comment by I3imbel** [comment]
I just copied the knot in the text editor, changed the number behind the process input and imported it back in the flow.

![image](https://user-images.githubusercontent.com/56531430/99934136-6daa0700-2d5d-11eb-8462-2473ee07bf13.png)

**Comment by I3imbel** [comment]
I copied the knot in the text editor, changed the number behind the process input and imported it back to the flow:

![image](https://user-images.githubusercontent.com/56531430/99934409-2a03cd00-2d5e-11eb-905e-db22e0a2d4ce.png)

**Comment by pwcutajar** [comment]
HI

A bit new to this, i have a flow that turns a tasmota device on and off, but cant work out how to tell alexa its on or off. the above has been done can anybody show me / discuss what im doing wrong? its a sonoof mini with an external switch hence i need to feed the power state back. 

cheers

**Comment by fmuntean** [comment]
when I export the node as JSON my node has the processingInput:1 but still not working.

**Comment by pwcutajar** [comment]
ip put this in a function

var nodeid="f49dfa34.2e1fb8";

if (msg.payload == "ON"){
    msg.payload = {
        on: true,
        nodeid: nodeid
    }

} else if(msg.payload == "OFF"){
    msg.payload = {
        on: false,
        nodeid: nodeid
    }
}

return msg;

then put it between the MQTT listen and the Alexa hub. You MUST edit the node id (top line) to match that of the alexa device node.

I have noticed that this works perfect on the alexa andriod app but my echo show 5 doesnt change the lights status unless to click away from the the device view and re select it. it doesnt seem to refresh the graphic.

**Comment by datech** [comment]
For more information on why it is not supported, please see #196.
