### ISSUE TITLE
dont work for me

### ISSUE THREAD

**Issue by eduardocanton** [datech/node-red-contrib-amazon-echo#14]
Hello,

##### SUMMARY
I have a node-red (v0.19.5) with node 6.11.2 on a raspberry pi 3.

##### ECHO DEVICES
My devices are a Echo v2 and a Echo Plus v2.

i install : npm install node-red-contrib-amazon-echo
and install withour error.

in my console appears the two icons, but in the first deploy (or reload page) , node-red response with a "stop flow" error and the 2 icons disapears. and I have two new lines on console:

4 Feb 16:50:04 - [info]  - node-red-contrib-amazon-echo:amazon-echo-hub : SyntaxError: Unexpected token *
4 Feb 16:50:04 - [info]  - node-red-contrib-amazon-echo:amazon-echo-device : SyntaxError: Unexpected token

**Comment by datech** [comment]
Hello, 

Can you share your flow?

Have you tried to install it using manage palette?

**Comment by Barabba11** [comment]
yes, be sure you are not running node red with root permission, very important.
Use palette to install everything. In my case installing from command line *never* worked, and I don't know why people still report it, use only palette.

**Comment by jfitton74** [comment]
Hi
I am having the same issue with Flows stopping, my flow just contains the "amazon echo hub" widget, press deploy and recieve error message saying "flows stopped due to missing node types - amazon-echo-hub". When looking at the palette manager there is a red warnign triangle with [object object] to the left.

If I delete the widget and redeploy the error goes away.

Node red is v0.19.5

Flow is 
[{"id":"e345a526.97b7b8","type":"amazon-echo-hub","z":"c736923b.ca482","port":"80","enableinput":false,"x":722.0764312744141,"y":344.6458511352539,"wires":[[]]}]

**Comment by datech** [comment]
@jfitton74 Have you used manage palette to install the module?

**Comment by jfitton74** [comment]
Hi sorry should have mentioned that, I installed via the manage palette.

**Comment by datech** [comment]
May I ask you to enable the debug logging on Node-RED and try to install and deploy again?

https://nodered.org/docs/user-guide/logging
Just switch level to debug and restart the Node-RED.

I'm interesting to see if there are any errors or debug messages in Node-RED console log.

**Comment by jfitton74** [comment]
I was using a docker instance, but when I moved to a full linux install it working without issue, just now need to fix mDNS for that VLAN.

**Comment by PTS93** [comment]
I had the exact same issue as @eduardocanton . I was also running the same combination of node-red version and node.js version. Upgrading from Node 6 to Node 10 (and restarting node-red of course) fixed this issue for me. Probably a feature of later node version that wasn't supported.

For those too lazy to google around, this is the offical install script for debian based distro, works also for the Pi.
`curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -`

**Comment by alexschwantes** [comment]
@PTS93 This worked for me 👍 
Was running Node-RED version: v0.16.1 & Node.js  version: v6.9.4 on the raspberry pi and was getting these same errors. Your command to upgrade to node 10 fixed it. (after i also had to update a bunch of other node red modules)
