### ISSUE TITLE
Tapparella

### ISSUE THREAD

**Issue by antonello69** [datech/node-red-contrib-amazon-echo#140]
Aiuto per Tapparella sto usando node-red-contrib-amazon-echo e non riesco a scrivere una funzione per far funzionare le tapparelle, mentre per le luci e le prese va tutto bene qualcuno puo aiutarmi? grazie
![echo hub](https://user-images.githubusercontent.com/46422002/89545286-72c16580-d803-11ea-9999-c56132684612.jpg)

**Comment by Barabba11** [comment]
The function you wrote contain an error, it outputs something that create problem to the following node.
You can post here your code, without it it's impossible to help you

**Comment by antonello69** [comment]
Questo è il codice della funzione che stavo provando
`if`` (msg.payload === "on")
msg.payload =
{
    "service": "turn_on",
    data:
    {"position": msg.position,}
};
if (msg.payload === "off") msg.payload = {"service": "turn_off"}
return msg;` 

Sinceramente` non so come fare questa funzione le altre due funzioni delle luci e delle prese l'ho copiato da questo video https://www.youtube.com/watch?v=l1as3tYVy64

**Comment by Barabba11** [comment]
Ci sono molti errori, qui c'è il codice corretto:
if (msg.payload == "on") {msg = {payload:{ service: "turn_on", data: {position: msg.position,} } } }
if (msg.payload == "off") {msg = {payload:{ service: "turn_off", data: {position: msg.position,} } } }
return msg;
in questo forum si scrive in inglese per dare la possibilità a tutti  di capire, ma il tuo problema è il javascript e non il modulo in questione :)

**Comment by antonello69** [comment]
first of all I apologize if I wrote in Italian however this function continues to give me api error

**Comment by Barabba11** [comment]
I'm not sure you are passing the right object structure to the next module, use debug node to check it. I suggest you to carefully read a guide about JavaScript and objects

**Comment by antonello69** [comment]
OK I will try but it will be very difficult I am just zero for javascript

**Comment by Barabba11** [comment]
Nobody born teacher )) if you like to deal with Node Red, than it's worth to study it, you will have lot of satisfactions )
