### ISSUE TITLE
Use same Hub in multiple flows

### ISSUE THREAD

**Issue by alexmilde** [datech/node-red-contrib-amazon-echo#141]
**Thanks:** 
thank you so much for your work. Its amazing!

**Is your feature request related to a problem? Please describe.**
I splitted my flows into multiple "tabs" in node red. But I cant add the Hub node multiple times. (I can but port conflicts and it doesnt seem to work that way)

**Describe the solution you'd like**
Add key to hub instance. 
Add new node which solely works as a reference to the hub instance

**Describe alternatives you've considered**
Right now I've put all Alexa related flow on one chart, but now i have an "almost identical" flow on two tabs which breaks the dont repeat yourself paradigma.

**Disclaimer**
I'm pretty new to node-red so there might be a better solution to my problem.

**Comment by datech** [comment]
Have you tried using **Link in** and **Link out** nodes?

**Comment by alexmilde** [comment]
Thanks. This works.

**Comment by commandcontrolit** [comment]
Oh thanks! Somehow I missed this issue! I will give this a go!

Thanks!
