### ISSUE TITLE
Identify device from which a voice command originated, so I can send TTS to that device only.

### ISSUE THREAD

**Issue by cibernox** [datech/node-red-contrib-amazon-echo#143]
I don't know if this is the right place, but I want to create alexa routines to *ask* alexa various stuff:
- Alexa, how long until the washer ends? (Checks remaining time of current wash cycle)
- Alexa, when did Mary leave? (Reads the time when Mary's phone left the geofenced region)

I was able to create virtual switches for those questions in node-red and trigger voice responses. What I don't know is how to send the response only to the alexa device to which I asked the question.

Is there a way of knowing what alexa device handled the command and make it part of the payload so I can use it when using alexa_media_player's text-to-speech?

I'm relatively new to node red, so if this is not something this package can/should handle I'd appreciate any direction on where to look.

Thanks

**Comment by zaphod2010** [comment]
check this out - this is what I am using with Hass.io and node-red. It's a homeassistant custom component.

https://github.com/custom-components/alexa_media_player/wiki#creating-sensorlast-alexa

a virtual sensor always shows the last alexa device - so very likely the one you talked to.

Not sure if this works for you as it depends on homeassistant.

**Comment by cibernox** [comment]
It does work, I just tried. I didn't consider that. However I still think that having the device name or ID from which a command originated, if not very complex to implement, would be a nice addition. 

While the chances of two members of the family giving commands to two amazon devices that close in time that the last_alexa sensor is not the one you spoke to is slim, it still non-zero. The author of the library can weight on it.

But for now I can use that trick, I worked beautifully. Thanks!

**Comment by datech** [comment]
All, 

It was discussed a few times already that only master Alexa device is communicating with the hub. That’s why we have only the IP address of the master device that can be used as identifier. If you use a single account for all Alexa devices then you will have only one master in the network.

**Comment by cibernox** [comment]
So, its a limitation of the way alexa platform reports commands, correct?

**Comment by datech** [comment]
Yep, it is a limitation.

It was documented in the help.

> meta.insert.details.ipstring
> Alexa master device IP address.
> Only if meta.insert.by=alexa

But it looks like people are missing it. Maybe I need to create a separate topic in the troubleshooting wiki page. Any ideas on how we can make this more visible and clear?

**Comment by cibernox** [comment]
Where exactly is it mentioned? TBH I only checked the readme, the wiki and a google, but it there are so many results including alexa and node-red that it was noise.

I think that mentioning it in the troubleshooting and also mentioning creating a last_alexa sensor in Home Assistant as a possible scape hatch would have worked for me.

**Comment by datech** [comment]
It is mentioned in the **Node help** of **Alexa Echo Hub Node**

<img src="https://user-images.githubusercontent.com/535026/92974318-99bc2880-f48e-11ea-87b7-ea149d60fcb3.png" width="600"/>

Ok, I will add it to the wiki.

**Comment by Barabba11** [comment]
> I don't know if this is the right place, but I want to create alexa routines to _ask_ alexa various stuff:
> 
>     * Alexa, how long until the washer ends? (Checks remaining time of current wash cycle)
> 
>     * Alexa, when did Mary leave? (Reads the time when Mary's phone left the geofenced region)
> 
> 
> I was able to create virtual switches for those questions in node-red and trigger voice responses. What I don't know is how to send the response only to the alexa device to which I asked the question.
> 
> Is there a way of knowing what alexa device handled the command and make it part of the payload so I can use it when using alexa_media_player's text-to-speech?
> 
> I'm relatively new to node red, so if this is not something this package can/should handle I'd appreciate any direction on where to look.
> 
> Thanks

Hi, unfortunately I can't understand all you wrote in English, it's not clear your purpose.. you want to ask Alexa "Alexa, when did Mary leave?" With this module? And how this is possible? This module simulates a bulb, how you can pretend Alexa sends to the bulb the answer? How then can Alexa give you back the answer? Probably she can just tell it.

About which Alexa accepted and sent the request.. if it wasn't the master it's impossible to understand it, so you need to make all them masters.. so you need to associate each with different account

**Comment by cibernox** [comment]
@Barabba11 what I wanted is to know from which echo device did the user trigger a command (in this case, a question) so I could send the answer to that device only. I've solved that with the trick mentioned

**Comment by Barabba11** [comment]
thanks for answer, we're talking about datech module and it simulates a philips bulb, now how you can ask a bulb "emaining time of the washing cicle"? I don't understand this, probably it's not involved with this module.
Anyway, what is also the sense to check which Echo replied, if there are different echos ready to repat on the same question it means they have discovered the same device, for example "living room lights", as I dubt you put 2 echos in the sema room there should be 2 living rooms (maybe in different floors), so all Echos will discover both living rooms.. and that's not so great. This is why I asked what for..

**Comment by gnuhel** [comment]
@cibernox Can we do something similar to what @zaphod2010 said with https://github.com/custom-components/alexa_media_player/wiki#creating-sensorlast-alexa?

**Comment by cibernox** [comment]
@gnuhel That's what I ended up doing, and it works reasonably well.

**Comment by gnuhel** [comment]
@cibernox What I mean is, can we implement the same way alexa media player does in node-red-contrib-amazon-echo?

**Comment by cibernox** [comment]
@gnuhel In my case I create that sensor in home assistant, but having it in node-red itself would be handy, at the end I have all my automations in node-red.
We just need to take into account that, while the chances are slim, there's a possibility that two people send commands in different rooms almost at the same time and the response could get routed to the wrong one. Not that there's anything we can do, just make it clear that it only works 99.9% of the time.

**Comment by gnuhel** [comment]
For me it also works. I add 1 sec delay before asking for the sensor.last_alexa. This way it works more reliable.
