### ISSUE TITLE
Port 80 error when hub and device nodes placed in more than one flow

### ISSUE THREAD

**Issue by commandcontrolit** [datech/node-red-contrib-amazon-echo#147]
##### SUMMARY
The node runs just fine, but only when in a single flow. If I try to use the hub and the device node in another flow, I receive the error message:
**Error: listen EADDRINUSE: address already in use :::80"**

##### ECHO DEVICES
* Echo Plus 2nd generation 
-->

##### MODULE VERSION

```
0.1.10
```

##### CONFIGURATION

```
[{"id":"e520dde6.25263","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"6b313860.4bb1e8","type":"amazon-echo-device","z":"e520dde6.25263","name":"Office TV","topic":"","x":380,"y":280,"wires":[[]]},{"id":"43d82c91.26dd14","type":"amazon-echo-hub","z":"e520dde6.25263","port":"80","processinput":0,"discovery":true,"x":250,"y":360,"wires":[["6b313860.4bb1e8"]]}]

[{"id":"60dc4b86.f42664","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"5a2fc4e6.3358cc","type":"amazon-echo-device","z":"60dc4b86.f42664","name":"Kitchen Light","topic":"","x":270,"y":280,"wires":[[]]},{"id":"7ddca4c8.d8a3fc","type":"amazon-echo-hub","z":"60dc4b86.f42664","port":"80","processinput":0,"discovery":true,"x":130,"y":360,"wires":[["5a2fc4e6.3358cc"]]}]
```

##### CONSOLE OUTPUT

```
**Error: listen EADDRINUSE: address already in use :::80"**
```

##### STEPS TO REPRODUCE

Place the hub and device nodes in more than 1 flow
##### EXPECTED RESULTS

No errors and the node works in as many flows as it's placed in.
##### ACTUAL RESULTS
**Error: listen EADDRINUSE: address already in use :::80"**

**Comment by Barabba11** [comment]
#datech friend, I think it's better you improve your troubleshooter to avoid such daily issues (

**Comment by commandcontrolit** [comment]
Sorry, I don't understand your response? I don't see guidance on how to resolve this issue.

**Comment by commandcontrolit** [comment]
> #datech friend, I think it's better you improve your troubleshooter to avoid such daily issues (

Sorry, I don't understand your response? I don't see guidance on how to resolve this issue.

**Comment by Barabba11** [comment]
There is a parallel topic with similar situation. We would need a detailed troubleshooter to avoid same questions

**Comment by commandcontrolit** [comment]
> There is a parallel topic with similar situation. We would need a detailed troubleshooter to avoid same questions

Ah ok. That seemed slightly different to my problem. With that problem, the node would not work at all. Mine works, but only when in 1 flow. 

Maybe I'm incorrect?

How can I help with troubleshooting? Happy to do so!

**Comment by datech** [comment]
Duplicate to #141

**Comment by commandcontrolit** [comment]
Oh thanks! Somehow I missed this issue! I will give this a go!

Thanks!
