### ISSUE TITLE
Only ON/OFF Messages returned from hub

### ISSUE THREAD

**Issue by DrMucki** [datech/node-red-contrib-amazon-echo#148]
Hi
I have got the problem that, whatever I ask Alexa the node only gives back "on" or "off" values. no brightness no color etc.

I use node red in a docker. As described in the Troubleshooting of the WIKI I run the docker as root (user 0) with host network access. There are only 2 more containers with zigbee2mqtt and mosquito running. None of them is using port 80.

Alexa finds my "Testlampe" without problems. When I use the Alexa App or ask her to switch off or on the "Testlampe"
 I get a msg.payload "on" or "off" as expected. But when I change color or brightness. It also gives back "on" or "off".

my node looks like this so far

<img width="503" alt="Bildschirmfoto 2020-10-28 um 18 01 24" src="https://user-images.githubusercontent.com/56001682/97470430-cc8b8480-1947-11eb-83c6-6b480cdf0cbd.png">

What am I doing wrong??

**Comment by datech** [comment]
Debug the entire msg, not just the msg.payload.

**Comment by DrMucki** [comment]
I apologize for my ignorance...... Thank you for your help
