### ISSUE TITLE
Add RGB color as hub input

### ISSUE THREAD

**Issue by datech** [datech/node-red-contrib-amazon-echo#15]
Add support of RGB color as hub input

**Comment by scargill** [comment]
Could you PLEASE add the ability to change to EGB colormode via the input - it is proving nigh on impossible to get accurate conversion from an RGB input to HS mode and thid is needed it (in addition to the alexa node changing colour) an external RGB controller is also changing the colour. The only RGB-HSV convertor for NR that I'm aware of works with 0-360, 0-100 and 0-100 output values given 0-255,0-255,0-255 RGB input.

**Comment by datech** [comment]
Released in v0.1.10

**Comment by scargill** [comment]
Magic…
