### ISSUE TITLE
Device could only be switched a few times

### ISSUE THREAD

**Issue by Aendrew87** [datech/node-red-contrib-amazon-echo#151]
Hi, I have a issue like discuessed in #150.

Environment:
- Tasmota-Devices (Tasmota 8.5.0 by Theo Arends) with emulation (Belkin WeMo single device)
- ioBroker (4.0.10) with node-red (1.2.2) and sonoff (2.3.3) on a pi 4 4GB
- node-red-contrib-amazon-echo (0.1.10) (Amazon Echo Hub is running on port 80)
- Echo Dot (3. Gen.)
- Fritz!Box 7490 (no VLANs)

I tried to switch the Tasmota-Devices using Alexa app on my phone but after switching them off i could not switch them on.
After waiting a few hours switching on is possible for a few times und then i get error "Das Geräte reagiert nicht" (the device is not responding).

So i used node-red-contrib-amazon-echo to create a new device and switch the Tasmota-Devices using sonoff.
This is working for a few switches und then i also get error "Das Geräte reagiert nicht" (the device is not responding).

I used Amazon Smart Plug in the Alexa app to and this device is switching all the time without any error.

How could i debug / see the requests send to the Amazon Echo Hub?

**Comment by jeroenst** [comment]
I have the same issue, how did you solve this?

**Comment by Aendrew87** [comment]
@jeroenst my problem was, that alexa controlles the devices.
When disconnecting the alexa, which is managing the connections, it is not possible to control the switches.

Solution: Just dont disconnect the "main" alexa.

**Comment by Barabba11** [comment]
Solution2: leave this, use virtual smart home node and subscribe each echo to the same account. Switch off any Echo and keep it running

**Comment by jeroenst** [comment]
Unfortunately I can't use virtual smart home, I get this error in Amazon:
You are not eligible to enable this skill due to geographical restrictions.

**Comment by Barabba11** [comment]
Not all languages are supported, find your solution anche change the address. For example I'm Italia living in Russia, I declared  her I'm loving in Italy, all ok

**Comment by jeroenst** [comment]
Strange that language creates a geo restriction, I live in the Netherlands but I speak perfectly English....

**Comment by Barabba11** [comment]
unfortunately my freind, I also don't understand why. Give you a chance to move Echo in England, hopefully you won't need to ask Alexa for the weather and time services :(
Try to figure out something at Amazon support
