### ISSUE TITLE
Color and brightness not delivered to NodeRed

### ISSUE THREAD

**Issue by Jarod2801** [datech/node-red-contrib-amazon-echo#152]
Hi,

I created some devices, all working fine for switching on/off.

Now i want to go one step further and bring brightness and color from Alexa/Echo to NodeRed.

But when  connect a debug node to the output of the device node, the payload just has ON or OFF in it, no color or brightness information.

Am I doing something wrong?

In Alexa, I can switch ON/OFF, adjust color and brightness, but result is always just ON of OFF in NodeRed.

Any ideas.

BR
Jarod

**Comment by datech** [comment]
Duplicate to #148

**Comment by nayneyT** [comment]
Hi Jarod.

I had the same issue. The reason is only on or off is set in the msg.payload.

The full msg does however contain all the information you require. It's just a case of amending the msg.payload to meet you needs.

I wrote this function to write the payload data I needed for home assistant web socket.

```js
var data = {data: 
    {
        "transition":2,
        //"brightness": msg.bri,
        "brightness_pct": msg.percentage,
        "rgb_color": [msg.rgb[0], msg.rgb[1], msg.rgb[2]],
        //"color_name": ,
        //"hs_color": [msg.hue, msg.sat],
        //"xy_color": [msg.xy[0], msg.xy[1]],
        //"color_temp": msg.ct,
        //"kelvin": ,
        //"white_value": ,
        //"brightness_step": ,
        //"brightness_step_pct": 10,
        //"profile": ,
        //"flash": ,
        //"effect: "
    }};

//var data = {"data":{"transition":"1","brightness_pct":"100"}};

msg.payload=data
return msg;
```

The code above works for setting the brightness percentage and colour of a bulb. A lot of it is commented out and you will need amend it slightly to suit your needs.

Simply drag a function node onto your flow. Paste in the code. Connect the function between the 'Amazon Alexa Device' node and the 'home assistant web socket service' call node. Leave the data field empty as the function node will send the required data object to the service call.

![Screenshot_20201216-015520](https://user-images.githubusercontent.com/37027153/102294697-c8d8af00-3f41-11eb-9d39-8b3209f0d5cb.png)

![Screenshot_20201216-015502](https://user-images.githubusercontent.com/37027153/102294723-d726cb00-3f41-11eb-9d01-49d090511a00.png)

**Comment by LT-FoAmY** [comment]
Does anyone have a would anyone be able to provide a detailed breakdown of the entire msg object and it's properties and values... When setting light color to blue I get the expected 0,0,254 rgb value as expected, but when then switching color to white, nothing changes and the rgb array values stay the same. 
Would be helpful to have a breakdown of each property that can be received and range of values that can be expected from them.

**Comment by nayneyT** [comment]
Hi,

When I say: "Alexa set light A to Blue" then following is sent and the light turns blue:

```
object
on: true
bri: 254
percentage: 100
hue: 43527
sat: 200
xy: array[2]
0: 0.13550301400290363
1: 0.03987867049354716
ct: 199
rgb: array[3]
0: 54
1: 57
2: 255
colormode: "hs"
meta: object
payload: "on"
deviceid: "abc"
topic: ""
_msgid: "abc.123"
```

When I say "Alexa set light A to white" the following is sent and the light turns white:

```
object
on: true
bri: 254
percentage: 100
hue: 1092
sat: 10
xy: array[2]
0: 0.32272672086556803
1: 0.32902290955907926
ct: 199
rgb: array[3]
0: 255
1: 246
2: 245
colormode: "hs"
meta: object
payload: "on"
deviceid: "abc"
topic: ""
_msgid: "abc.123"
```

Can you elaborate further on your issue so that I can maybe assist?

Regards

**Comment by resodchym** [comment]
Hi @nayneyT 

first thanks for your advice. I have just followed your steps and setted the nodes and I can finally control lamps color.
But I have the similar problem as @LT-FoAmY , says, I can not turn the lamp back to white. And I can not turn of the lamp by saying: Alexa, trun off the light.

Wenn I say: Set the lamp to yellow I got:
```
object
on: true
bri: 254
percentage: 100
hue: 43690
sat: 254
xy: array[2]
ct: 284
rgb: array[3]
0: 0
1: 0
2: 254
colormode: "hs"
meta: object
payload: object
deviceid: "e903c5d9c27c28"
topic: ""
_msgid: "b0121efe.af903"
```
And wenn I say "Set the lamp to white" I got:
```
object
on: true
bri: 254
percentage: 100
hue: 43690
sat: 254
xy: array[2]
ct: 284
rgb: array[3]
0: 0
1: 0
2: 254
**colormode: "ct"**
meta: object
payload: object
deviceid: "e903c5d9c27c28"
topic: ""
_msgid: "cbc7b6d5.2e1808"
```

I mentioned here that the colormode switched from "hs" to "ct".

And further more, wenn I say "turn off the light" I got:
```
object
on: false
bri: 254
percentage: 100
hue: 43690
sat: 254
xy: array[2]
ct: 284
rgb: array[3]
0: 0
1: 0
2: 254
colormode: "ct"
meta: object
payload: object
deviceid: "e903c5d9c27c28"
topic: ""
```
But the lamp does not turn off. 

Have you any Idea? Thanks

**Comment by Barabba11** [comment]
have a try with node-red-contrib-virtual-smart-home

**Comment by datech** [comment]
The payload contains only 'on/off.' You may use a debug node to see the entire message, just select **complete msg object** for the output. Information about all fields of the output object can be found in the Hub Node documentation.
