### ISSUE TITLE
ALEXA IN NODE-RED ON CLOUD

### ISSUE THREAD

**Issue by MullerEsposito** [datech/node-red-contrib-amazon-echo#153]
**Is your feature request related to a problem? Please describe.**
I have a Node-RED hosted on IBMCloud. Is it possible connect my local Echo Dot to Node-Red on Cloud though the amazon-echo node?

**Comment by Barabba11** [comment]
You probably don't got how this module works, there is no sense to put it on internet since is made to work without internet. I suggest you to use the alexa skill module

**Comment by datech** [comment]
The idea is to utilize this module in a local environment. Although it's possible to run this module and Node-RED in the cloud, you would need to redirect all network requests to simulate that the Node-RED Amazon Echo Hub is operating within your local broadcast domain.
