### ISSUE TITLE
Use Alexa Range Controller / Semantics for more commands.

### ISSUE THREAD

**Issue by glennpierce** [datech/node-red-contrib-amazon-echo#155]
Is it possible to use the Alexa Range Controller / Semantics api to allow for more commands.
For example allow for saying

Alexa raise / lower or open / close the blinds etc.

There was the same issue opened for /node-red-alexa-home-skill-v3-web below that was resolved. So I assume its possible.

https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/86

Thanks

**Comment by datech** [comment]
This module will support only lights. You may use Alexa routines to simulate different types of devices and commands. To support a broader range of devices, an Alexa Skill will be needed. More information can be found in issue https://github.com/datech/node-red-contrib-amazon-echo/issues/196.
