### ISSUE TITLE
Recurrent error in syslog

### ISSUE THREAD

**Issue by MattL0** [datech/node-red-contrib-amazon-echo#158]
hi ,

I am getting this error every 5 seconds in linux syslog, 

`Jan  2 12:58:01 edited* Node-RED[1017]: TypeError: Cannot read property 'startsWith' of undefined
Jan  2 12:58:01 edited* Node-RED[1017]:     at followParentContext (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js:205:18)
Jan  2 12:58:01 edited* Node-RED[1017]:     at Object.value (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js:273:34)
Jan  2 12:58:01 edited* Node-RED[1017]:     at getOrDefault (/opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:316:32)
Jan  2 12:58:01 edited* Node-RED[1017]:     at getDeviceAttributes (/opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:384:12)
Jan  2 12:58:01 edited* Node-RED[1017]:     at getDevicesAttributes (/opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:393:24)
Jan  2 12:58:01 edited* Node-RED[1017]:     at /opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:226:17
Jan  2 12:58:01 edited* Node-RED[1017]:     at Layer.handle [as handle_request] (/opt/node-red/node_modules/express/lib/router/layer.js:95:5)
Jan  2 12:58:01 edited* Node-RED[1017]:     at next (/opt/node-red/node_modules/express/lib/router/route.js:137:13)
Jan  2 12:58:01 edited* Node-RED[1017]:     at Route.dispatch (/opt/node-red/node_modules/express/lib/router/route.js:112:3)
Jan  2 12:58:01 edited* Node-RED[1017]:     at Layer.handle [as handle_request] (/opt/node-red/node_modules/express/lib/router/layer.js:95:5)
Jan  2 12:58:01 edited* Node-RED[1017]:     at /opt/node-red/node_modules/express/lib/router/index.js:281:22
Jan  2 12:58:01 edited* Node-RED[1017]:     at param (/opt/node-red/node_modules/express/lib/router/index.js:354:14)
Jan  2 12:58:01 edited* Node-RED[1017]:     at param (/opt/node-red/node_modules/express/lib/router/index.js:365:14)
Jan  2 12:58:01 edited* Node-RED[1017]:     at Function.process_params (/opt/node-red/node_modules/express/lib/router/index.js:410:3)
Jan  2 12:58:01 edited* Node-RED[1017]:     at next (/opt/node-red/node_modules/express/lib/router/index.js:275:10)
Jan  2 12:58:01 edited* Node-RED[1017]:     at /opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:168:7`

`Jan  2 12:58:06 edited* Node-RED[1017]: TypeError: Cannot read property 'startsWith' of undefined
Jan  2 12:58:06 edited* Node-RED[1017]:     at followParentContext (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js:205:18)
Jan  2 12:58:06 edited* Node-RED[1017]:     at Object.value (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js:273:34)
Jan  2 12:58:06 edited* Node-RED[1017]:     at getOrDefault (/opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:316:32)
Jan  2 12:58:06 edited* Node-RED[1017]:     at getDeviceAttributes (/opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:384:12)
Jan  2 12:58:06 edited* Node-RED[1017]:     at getDevicesAttributes (/opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:393:24)
Jan  2 12:58:06 edited* Node-RED[1017]:     at /opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:226:17
Jan  2 12:58:06 edited* Node-RED[1017]:     at Layer.handle [as handle_request] (/opt/node-red/node_modules/express/lib/router/layer.js:95:5)
Jan  2 12:58:06 edited* Node-RED[1017]:     at next (/opt/node-red/node_modules/express/lib/router/route.js:137:13)
Jan  2 12:58:06 edited* Node-RED[1017]:     at Route.dispatch (/opt/node-red/node_modules/express/lib/router/route.js:112:3)
Jan  2 12:58:06 edited* Node-RED[1017]:     at Layer.handle [as handle_request] (/opt/node-red/node_modules/express/lib/router/layer.js:95:5)
Jan  2 12:58:06 edited* Node-RED[1017]:     at /opt/node-red/node_modules/express/lib/router/index.js:281:22
Jan  2 12:58:06 edited* Node-RED[1017]:     at param (/opt/node-red/node_modules/express/lib/router/index.js:354:14)
Jan  2 12:58:06 edited* Node-RED[1017]:     at param (/opt/node-red/node_modules/express/lib/router/index.js:365:14)
Jan  2 12:58:06 edited* Node-RED[1017]:     at Function.process_params (/opt/node-red/node_modules/express/lib/router/index.js:410:3)
Jan  2 12:58:06 edited* Node-RED[1017]:     at next (/opt/node-red/node_modules/express/lib/router/index.js:275:10)
Jan  2 12:58:06 edited* Node-RED[1017]:     at /opt/node-red/node_modules/node-red-contrib-amazon-echo/index.js:168:7`

**Comment by datech** [comment]
I cannot reproduce this issue with node-red-contrib-amazon-echo v0.1.11, Node-RED 3.1.18, and Node.js v16.20.2.
