### ISSUE TITLE
Discovery Issus

### ISSUE THREAD

**Issue by Gutleben** [datech/node-red-contrib-amazon-echo#159]
##### SUMMARY
After activate the node and set port to 8050 the device can't be found by alexa (from android mobile app)
Currently i run node-red under windows for testing purpose
When i call the 8050 port on localhost it says 
"Cannot GET /"
UPNP Scanner even cannot get the device informations

##### ECHO DEVICES
Echo Dot (currently offline)
Bose Soundbar 700 (active)

##### MODULE VERSION
node-red v.1.2.7
node.js 14.151

##### CONFIGURATION

```paste below

```

##### CONSOLE OUTPUT
C:\Windows\system32>node-red
6 Jan 22:17:30 - [info]

Welcome to Node-RED
===================

6 Jan 22:17:30 - [info] Node-RED version: v1.2.7
6 Jan 22:17:30 - [info] Node.js  version: v14.15.4
6 Jan 22:17:30 - [info] Windows_NT 10.0.18363 x64 LE
6 Jan 22:17:30 - [info] Loading palette nodes
6 Jan 22:17:31 - [info] Dashboard version 2.26.1 started at /ui
6 Jan 22:17:31 - [info] Settings file  : \Users\IvoGutleben\.node-red\settings.js
6 Jan 22:17:31 - [info] Context store  : 'default' [module=memory]
6 Jan 22:17:31 - [info] User directory : \Users\IvoGutleben\.node-red
6 Jan 22:17:31 - [warn] Projects disabled : editorTheme.projects.enabled=false
6 Jan 22:17:31 - [info] Flows file     : \Users\IvoGutleben\.node-red\flows_GS-RYZEN-IG.json
6 Jan 22:17:31 - [info] Server now running at http://127.0.0.1:1880/
6 Jan 22:17:31 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

6 Jan 22:17:31 - [info] Starting flows
6 Jan 22:17:31 - [info] Started flows
6 Jan 22:17:31 - [info] [loxone-miniserver:e297048b.e7ccc8] Miniserver connected (10.13.3.105:80) using Token-Enc
6 Jan 22:17:31 - [info] [loxone-miniserver:e297048b.e7ccc8] got structure file 2021-01-05 19:35:23

##### STEPS TO REPRODUCE
Install node-red under windows
start node-red
activate alexa-echo modul
add echo hub to flow
publish

##### EXPECTED RESULTS
alexa should find the device behind the hub

##### ACTUAL RESULTS
alexa don't find the device behind the hub

**Comment by datech** [comment]
New Echo devices could discover Amazon Echo Hub only on port 80
