### ISSUE TITLE
there is any way to setup this in subdomain?

### ISSUE THREAD

**Issue by mzramna** [datech/node-red-contrib-amazon-echo#164]
i don't know if this is directaly related to the alexa integration,or to nginx setup,but there is any way to integrate with subdomain?
i've tinking about it and the only way i can figure out to do it is to redirect all the requests to the port 80 with a specific patter related to the alexa api

**Comment by Barabba11** [comment]
Which is the reason for that, can you please make an example? Thanks

**Comment by mzramna** [comment]
i use some sub domains into my server,to isolate every docker container , but my nginx reverse proxy automaticaly redirect all the 80 requests to the 443 port,except by those to the node-red and home assistant subdomains,but i need to redirect to the api url instead of it,since this does not work,wich is this subfolder url? to redirect the requests to this url to the port 80 only

**Comment by nayneyT** [comment]
Hi. I am curious... why are you going via nginx?

Surely you are just adding _node-red-contrib-amazon-echo palette_ to your node-red running in a docker container?

**Comment by datech** [comment]
Closing as It is not related to the functionality of this module.
