### ISSUE TITLE
Alexa Smart Home devices trigger by themselves (switching without Alexa command)

### ISSUE THREAD

**Issue by Domi920** [datech/node-red-contrib-amazon-echo#167]
Hi,
I have problems with the palette "node-red-contrib-amazon-echo" version 0.1.10 (instance at IOBroker)
All Alexa devices created there trigger randomly again and again without Alexa giving the command.
That doesn't always happen every day, but sometimes only after a few days.

Here is the structure in NodeRed:

![Adapterkonfiguration node-red](https://user-images.githubusercontent.com/68474558/109522295-67d76680-7aae-11eb-8c85-b5aa7387cf5b.jpg)

![Skript 2021 03 01 (ohne Debug)](https://user-images.githubusercontent.com/68474558/109517465-9868d180-7aa9-11eb-9b10-9a8a8a02e1ae.jpg)
![Einstellungen Echo-Hub](https://user-images.githubusercontent.com/68474558/109517557-b3d3dc80-7aa9-11eb-8693-eb59170a5f9e.jpg)
![Einstellungen Smart Home Gerät Alexa](https://user-images.githubusercontent.com/68474558/109517632-c2ba8f00-7aa9-11eb-83f4-00ee386bb50e.jpg)
![Einstellungen Schalter ein aus](https://user-images.githubusercontent.com/68474558/109517589-ba625400-7aa9-11eb-85bb-90dea6d1c7d0.jpg)
![Einstellungen Funktion ein true](https://user-images.githubusercontent.com/68474558/109517671-cc43f700-7aa9-11eb-9847-56cceba72af7.jpg)
![Einstellungen Funktion aus false](https://user-images.githubusercontent.com/68474558/109517677-cf3ee780-7aa9-11eb-8436-2fb1bb9a6a53.jpg)
![Einstellungen Datenpunkt IOBroker](https://user-images.githubusercontent.com/68474558/109517695-d2d26e80-7aa9-11eb-9a5e-e80596c260d8.jpg)

In the IOBroker object list you can also see that all devices (including television mode) are controlled by node-red.

There are several Alexa devices in the network:
- Alexa Dot 1st generation
- Alexa Show (not 5 "not 8" variant, but first big one)
- Echot Dot 4th generation

Here are some data from IOBroker:
Node.js: v12.19.0
NPM: 6.14.8
node-red: V2.1.0 (IOBroker Instanz)

Otherwise everything works, only all devices trigger by themselves at the same time.

What can I do now?

Thanks in advance!

Greetings Dominik

**Comment by Karl0303** [comment]
Hey im dealing with the same problem at the moment. Did you find a solution for this very strange problem?

**Comment by Domi920** [comment]
Hello,
 unfortunately not.
 I'm using a different extension now:
https://flows.nodered.org/node/node-red-contrib-virtual-smart-home

Unfortunately, since the latest "fee" for more than 7 devices.
 But the 1€ is worth it to me.
 It offers many more benefits.


 Greetings Dominik

**Comment by Karl0303** [comment]
Hey Dominik, Thanks for your very quick feedback 😜🎉👍👍. I will try this tomorrow. Many greetingsKarl Am 04.11.22, 23:12 schrieb Domi920 ***@***.***>:

   
  Hello, unfortunately not. I'm using a different extension now: https://flows.nodered.org/node/node-red-contrib-virtual-smart-home 
  Unfortunately, since the latest "fee" for more than 7 devices. But the 1€ is worth it to me. It offers many more benefits. 
  Greetings Dominik

**Comment by Domi920** [comment]
No problem.
 I wish you success!
