### ISSUE TITLE
New modules that may work better

### ISSUE THREAD

**Issue by Barabba11** [datech/node-red-contrib-amazon-echo#172]
Hi mates, finally I had time to test other modules for Echo and I've to say I'm glad I did that. I hope the author won't argue me, but I suggest you to test:
1) node-red-contrib-virtual-smart-home
2) node-red-contrib-alexa-remote2v2

node-red-contrib-virtual-smart-home:  It works by internet.. and we need to consider that Alexa too.. without it can't work to recognize your voice so it's quite useless to have local devices. It it's extremely more compatible than this local module, no more problems about recognize duplicated names, have in list double devices or remove all of them manually from the app if you delete echo, have unworking devices if the list is too long, etc. All these issues are on the side of Echo firmware, not because of the author here/bugs, simply it seems new firmwares of Echo improved the skills compatibility and reduced it with local ones. This module connect to a skill which will simulate vrtual devices, and not just the light bulb.. many more! Another big plus.

node-red-contrib-alexa-remote2v2: This is about "do with Alexa extra things", like make her say something you want (you typed in Node Red), debug what she's dong, add to some words multiple functions (for example create scenarios), etc. Try that too! Interesting. Don't forget it's a bit buggy, but it's something worth to use.
Hope this will be useful for all

**Comment by Faustino-ai** [comment]
You saved me dude! Virtual smart home is awesome!

**Comment by cmille34** [comment]
Thanks for posting this!  I was having trouble with some device that had worked fine for a long time just not working anymore.  I removed it from Alexa and couldn't get it to rediscover anymore. I gave that virtual-smart-home a try and it picked it up instantly, no discovery needed even.
