### ISSUE TITLE
temperature

### ISSUE THREAD

**Issue by scargill** [datech/node-red-contrib-amazon-echo#18]
Feature requests rather than bugs. This Amazon-Echo node is already looking better than alexa-local - RGB input would make it even BETTER - BUT here (https://github.com/datech/node-red-contrib-amazon-echo) you say " Alexa, make the {device} warmer" is possible but trying that (I don't think it checks the actual light) fails. "Doesn't support that. Whether that means colour warm or temperature warm - COULD be used for temperature if it could increase some value or colour temperature?

node-red-contrib-alexa-local does not do warm but DOES ignore "temperature" so "alexa set mydevice to 35 degrees" sets a value to 20 - which could be used for temperature.... yours does not accept "set device to 20" and positively throws out "set device to 20 degrees" - a shame - any chance it could accept these in an update? 

Similarly "increase" and "decrease" could be used for light or temperature, your node does not accept increase - alexa-local does.  Any chance?

Possibly a switch to select one of two sets of features if you didn't want all that in one?

**Comment by datech** [comment]
Here is how it is working on Echo Dot 3rd gen.

**Alexa, make the {device} warmer**
```
6 Feb 20:28:16 - [debug] Request body: {"ct":220}
6 Feb 20:28:29 - [debug] Request body: {"ct":232}
6 Feb 20:28:35 - [debug] Request body: {"ct":246}
```

**Alexa, set {device} to 35 degrees**
**Alexa, set {device} to 45**
**Alexa, set {device} to 55 percentage**
```
6 Feb 20:38:19 - [debug] Request body: {"bri":90}
6 Feb 20:38:26 - [debug] Request body: {"bri":115}
6 Feb 20:38:33 - [debug] Request body: {"bri":140}
```

**Alexa, increase {device}**
**Alexa,  decrease {device}**
```
6 Feb 20:40:42 - [debug] Request body: {"bri":64}
6 Feb 20:40:47 - [debug] Request body: {"bri":1}
```

I don't have any control over what Alexa will send to the hub for any of the listed commands above.
Each voice command is sending API request to the Amazon Echo Hub Node, but what exactly will be send to the hub is configured by Amazon.

If you send me the console debug info for each command I may think for a possible change in this module in order to handle the missing API requests.

**Comment by scargill** [comment]
Hey thanks for that - taking yourf example with my arbitrarily named toilet light.. set device to 35 degrees etc works as does increase or decrease toilet light... but make toilet light warmer - I get not stpported - now why would that be? I cant se any missed settings? Why can you get that? I even renamed it to "toilet" for the sake of it. "toilet doesn't support that. I'm at a loss as to why your device does - after all its not a real device - juat a name.

**Comment by wongnam** [comment]
@scargill In my use case found that the Color Temperature is supported on Echo dot 3rd generation but Echo Dot 1st and 2nd generation is not supported.

**Comment by rkoebrugge** [comment]
I tried adding a Amazon Device with this addon and named it 'Bathroom temperature'. I tried setting the temperature to 20 degrees, but the debug output shows all Light properties like brightness and RGB properties. At the Alexa app I also see that the device was setup as Light (and Colour + Colour temperature capabilities) which I assume that it will always send properties based on lights. I cannot edit the device type to 'Thermostat', also not through a voice command.

Is it possible to get this app going with thermostat devices? Or how can we help to get this done?

**Comment by scargill** [comment]
I just bought 3rd generation dots for this.. I hope it works for temperature now. Warmer and cooler would be good even if I have to translate the result.

**Comment by datech** [comment]
@scargill Just note that you have to disconnect all old Echo devices during the discovery process in order to have the light device recognized only by Echo Dot 3rd gen

**Comment by datech** [comment]
@rkoebrugge Only light devices could be simulated with this module. I'm looking for a way to add more device types, like thermostats,  without using Alexa skills, but as for now, it looks like it is not possible.

**Comment by scargill** [comment]
Within limits resolved with gen 3 Amazon dots. Thanks.
