### ISSUE TITLE
Button Entity

### ISSUE THREAD

**Issue by FelipeDamasio** [datech/node-red-contrib-amazon-echo#180]
As everyone knows, now the new version of HA has a button entity, which makes it much easier to trigger automations instead of a toggle. In the documentation for the new version, it is said that this entity is available for Alexa. It would be great if I could add this functionality in Amazon Echo Contrib, because currently to trigger an automation on node red I need to configure it to turn on, wait 5 seconds and turn off for the Alexa app. If I could only send a "press" it would be much simpler and more functional.

Thanks!

**Comment by datech** [comment]
I'm not sure that such enhancements are related to the functionality this module provides. Feel free to reopen if we can relate it somehow.
