### ISSUE TITLE
Defining different types of devices

### ISSUE THREAD

**Issue by peterdermeter** [datech/node-red-contrib-amazon-echo#181]
Just tried this node for controlling my iobroker devices and it worked perfectly. 
Now i have the issue, that i want to "open" and "close" my garage door by alexa commands. Unfortunately this node only gives me an "on" and "off" command and this doesnt sound naturally.  It would be great if you could add a feature, so i can say "alexa, open/close garage".
Greetings

**Comment by elgerg** [comment]
I had the same issue with curtains. I ended up creating a routine to turn the curtains on and off....

**Comment by peterdermeter** [comment]
Thanks!
I already came to the same solution!

**Comment by datech** [comment]
The payload will contain only 'on/off.' You may use a debug node to see the entire message, just select '**complete msg object**' for the output. Information about all fields of the output object can be found in the Hub Node documentation.

This module will support only lights. You may use Alexa routines to simulate different types of devices and commands. To support a broader range of devices, an Alexa Skill will be needed. More information can be found in issue #196.
