### ISSUE TITLE
node-red-contrib-amazon-echo has 2 Versions?

### ISSUE THREAD

**Issue by MrThiemann** [datech/node-red-contrib-amazon-echo#183]
hey
I had to reinstall NodeRed and I am adding all the packages I was using.

Now i would install "[node-red-contrib-amazon-echo](https://flows.nodered.org/node/node-red-contrib-amazon-echo)", but i found "[node-red-contrib-amazon-echo-oztourer](https://flows.nodered.org/node/node-red-contrib-amazon-echo-oztourer)", too.
where are the differences here? Which version should I install now?

Thank you =)

**Comment by pauly7300** [comment]
The other is a fork of this one by another user.  Click the "View on github" link on the page you linked and you'll be able to see it's from a different user.
