### ISSUE TITLE
Add other home assistant entity types

### ISSUE THREAD

**Issue by neil1111** [datech/node-red-contrib-amazon-echo#187]
**Is your feature request related to a problem? Please describe.**
Have other entity types, such as covers, media, etc., so everything isn't treated as a Hue light.

**Describe the solution you'd like**
Per the above.

**Describe alternatives you've considered**
Not sure of others, beyond some of the other alexa node-red integrations that exist. But this one is very stable & reliable.

**Additional context**
Thank you!

**Comment by prbtt** [comment]
> **Is your feature request related to a problem? Please describe.** Have other entity types, such as covers, media, etc., so everything isn't treated as a Hue light.
> 
> **Describe the solution you'd like** Per the above.
> 
> **Describe alternatives you've considered** Not sure of others, beyond some of the other alexa node-red integrations that exist. But this one is very stable & reliable.
> 
> **Additional context** Thank you!

That i'll be very helpfull. For now, i'm using the function node to get covers and ac units working with alexa. All lights were moved inside a group in the alexa app and covers+ac outside, so when i ask alexa to turn the lights off, it doesn't mess them.

How i did the AC:
Used the brightness percentage payload to control the target temp. If it's above 28C it sends 28 and if its below 18, it sends 18.
```
let bri = msg.percentage
if (bri > 28) bri = 28
if (bri < 18) bri = 18
if (msg.payload === "on") msg.payload =
{
    "service": "set_temperature",
    data:
        { "hvac_mode": "cool", "temperature": bri }
};

if (msg.payload === "off") msg.payload = {"service":"turn_off"};

return msg;
```
How i did the Cover:
Same thing as AC, using the brightness percentage as cover position. If yout cover entity doesn't support cover position, you can make a routine in the alexa app that toggles the cover up and down or just on = open and off = close.

```
let pos = msg.percentage

if (msg.payload === "on") msg.payload =
{
    "service": "set_cover_position",
    data:
        { "position": pos }
};

if (msg.payload === "off") msg.payload = {"service":"close_cover"};

return msg;
```


> **Is your feature request related to a problem? Please describe.** Have other entity types, such as covers, media, etc., so everything isn't treated as a Hue light.
> 
> **Describe the solution you'd like** Per the above.
> 
> **Describe alternatives you've considered** Not sure of others, beyond some of the other alexa node-red integrations that exist. But this one is very stable & reliable.
> 
> **Additional context** Thank you!

**Comment by datech** [comment]
This module will support only lights. You may use Alexa routines to simulate a different types of devices and commands. To support a broader range of devices, an Alexa Skill will be needed. More information can be found here #196
