### ISSUE TITLE
Feed brightness % in from MQTT

### ISSUE THREAD

**Issue by harvybob** [datech/node-red-contrib-amazon-echo#193]
**Is your feature request related to a problem? Please describe.**
I have setup a dimmer (Tasmota using TuyaMCU). Turning it on/off dimmer is working ok -  I have set up the feedback as per the Wiki, which allows me to see the On/Off status on Alexa App. I am not able to set the brightness in this way AS A PERCENTAGE - only as the brightness value. MQTT has the value as a percentage so I have to do the math to convert from percentage back to brightness value.

**Describe the solution you'd like**
Using the example feedback in the Wiki, the currently I need to do this:

```
var dimmerval = (msg.payload.Dimmer / 0.4).toFixed(0);
if (msg.payload.POWER == "ON") {
    msg.payload = {
        on: true,
        bri: dimmerval,
        nodeid: nodeid
    }

```

I want to be able to do:
```
var dimmerval = msg.payload.Dimmer;
if (msg.payload.POWER == "ON") {
    msg.payload = {
        on: true,
        percentage: dimmerval,
        nodeid: nodeid
    }

```

**Describe alternatives you've considered**
Having to do the math to convert from % to dimmer value - isnt accurate due to rounding issues - Alexa cant handle decimal values between 0 and 250

**Additional context**
This may already be in place, but I am unable to use it correctly - if so, is there a list of the feedback values to use? I have tried percentage

**Comment by datech** [comment]
You may use range node to convert percentage to brightness (bri).

<img src="https://github.com/datech/node-red-contrib-amazon-echo/assets/535026/a2d3c21e-54fd-4fc4-bbf3-203e67a01a9d" width="50%" >
