### ISSUE TITLE
Issues with dimming, payload is always "on"

### ISSUE THREAD

**Issue by zulasch** [datech/node-red-contrib-amazon-echo#195]
##### SUMMARY
I was able to setup the connection succesfully, and connect my smart home devices. I am able to turn on and off the lights but not to dimm, the payload send out to the smart home device is only "on" but not the percentage value.
In the Amazon Alexa App I can see that the lamp was set succesfuly to the corresponding percentage value but the node is not sending that 

![2023-12-29 12_33_00-Node-RED _ Flow 1](https://github.com/datech/node-red-contrib-amazon-echo/assets/48367102/59315704-a8ca-4839-a6a1-2661d2144443)

##### ECHO DEVICES
Echo Studio

##### MODULE VERSION
```
0.1.10
```

##### CONFIGURATION

```
[
    {
        "id": "924ee0aaa511b299",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "c7c2a83324beade4",
        "type": "loxone-control-out",
        "z": "924ee0aaa511b299",
        "name": "Büro OG Licht",
        "miniserver": "1d0824610e5bcac0",
        "control": "40298e14-9236-11e3-b25eeaf4b4aa4561/AI1",
        "x": 720,
        "y": 640,
        "wires": []
    },
    {
        "id": "c46c62d862e9ca03",
        "type": "debug",
        "z": "924ee0aaa511b299",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 700,
        "y": 580,
        "wires": []
    },
    {
        "id": "25e195e6852969aa",
        "type": "amazon-echo-hub",
        "z": "924ee0aaa511b299",
        "port": "80",
        "processinput": 0,
        "discovery": true,
        "x": 130,
        "y": 640,
        "wires": [
            [
                "33c6f6baca2a4d49"
            ]
        ]
    },
    {
        "id": "33c6f6baca2a4d49",
        "type": "amazon-echo-device",
        "z": "924ee0aaa511b299",
        "name": "Buero",
        "topic": "",
        "x": 370,
        "y": 640,
        "wires": [
            [
                "c7c2a83324beade4",
                "c46c62d862e9ca03"
            ]
        ]
    },
    {
        "id": "1d0824610e5bcac0",
        "type": "loxone-miniserver",
        "host": "192.168.178.25",
        "port": "443",
        "enctype": "0",
        "active": true,
        "keepalive": "60000"
    }
]
```

##### CONSOLE OUTPUT
```
29.12.2023, 12:28:04[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:28:14[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[3]
"off"
29.12.2023, 12:31:53[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:31:54[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:31:56[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:31:58[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:31:59[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:32:00[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:32:02[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:32:13[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:32:15[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[2]
"on"
29.12.2023, 12:32:20[node: debug 1](http://192.168.178.201:1880/#)
msg.payload : string[3]
"off"
```

##### STEPS TO REPRODUCE
configure the node with a device and discover it via alexa, after that say "alexa, set my light to 50%" 
This seems to work by the payload send out from the node is "on" instead of "50%"

##### EXPECTED RESULTS
I expect that the percentage value is sent out as told to alexa

##### ACTUAL RESULTS
the acutal result is always "on" even if I say a percentage value

**Comment by colgrim** [comment]
Try debugging the complete object. Double-click on the debug node and change its output to "complete msg object" 

In the debug window you will get more information about the object, in which the alexa-node writes its data.

**Comment by zulasch** [comment]
I only have this options:
![image](https://github.com/datech/node-red-contrib-amazon-echo/assets/48367102/ce38d4c4-23d6-4851-a133-e621ee134198)

I activated all 3 options but the output is the same, only off or on even for dimming. 

I cant find any "complete msg object" or I am looking wrong?

**Comment by zulasch** [comment]
I got it! :D
![image](https://github.com/datech/node-red-contrib-amazon-echo/assets/48367102/abccbc2e-0c21-44dc-91be-d464c006d405)

now I can see the percentage parameter and can extract this for my smart home. 
![image](https://github.com/datech/node-red-contrib-amazon-echo/assets/48367102/0daf97d4-95fc-4595-b436-343668e9ef2d)

many thanks, that solved my issue
