### ISSUE TITLE
Node-Red Link and amazon echo nodes

### ISSUE THREAD

**Issue by scargill** [datech/node-red-contrib-amazon-echo#20]
Latest nodes, up to date Node-Red. I have a page of working smszon-alexa devices with one hub. I tried putting more on a second page. Of coures you can have only one hub (at leat on the same port).

So I hit the idea of using the NR LINK to link the hub to a second page of devices - doesn't work. Any idea why?

**Comment by frankyboy1973** [comment]
Hi, i am using Links to 4 other pages and it works fine.
![hublink1](https://user-images.githubusercontent.com/46169800/52800612-67f99a80-307c-11e9-8242-c591b84cc621.JPG)
![hublink2](https://user-images.githubusercontent.com/46169800/52800616-6af48b00-307c-11e9-910b-a63fb18b90f7.JPG)
