### ISSUE TITLE
Device discovery

### ISSUE THREAD

**Issue by scargill** [datech/node-red-contrib-amazon-echo#21]
With only one hug, at least with gen 3 Echo Dots - after the first node is added, subsequent nodes work but Echo says it cant find any new devices. I have maybe 10 devices on th page.

All software up to date and gen 3 Echos bought yesterday.

Any thoughts?

**Comment by Barabba11** [comment]
I don't understand well your English, by the way if can't find new divides how that can work?

**Comment by wongnam** [comment]
@scargill Echo Dot 3rd gen only work on port 80, if you chose to use port different to 80 (eg port:8000 >1024) then you have to use NAT solution to forward the port 8000 to 80, if your system or your Pi already used the port:80 that maybe it's difficult to deal with.

**Comment by datech** [comment]
@scargill I'm constantly testing the module by adding new devices and asking Alexa to run the discovery procedure again. Was the flow deployed?

**Comment by scargill** [comment]
IU'm running this constantly now, once we resolved the tables issue - I have it on port 8980... translated to 80. Its great. If only it could to temperature properly instead of having to cludge light values.  Turn heating up/down, set hesting to 15c... etc would be great. Mind you it does work better with gen 3 dot rather  than old gen1.

**Comment by datech** [comment]
Yep, I understand, but I don't have any control over this one. Echo device is selecting what to send ot the hub for each voice command. 

What about to adding a **range** node on the output of the device node?

**Comment by scargill** [comment]
I WILL do that, I have a requirement that, it seems none of the fancy stats out there meet...

a) The heating is air source heat punp and should only vary temperature by a small amount - ie a few degrees. Heating up in cold seather takes a long time. (s) whenour home is used for holiday rental in the summer (as we clear off to Spain) I need remote contol - but guest should get short term control only, within the limits we set. They must not be able to mess up timers... AND operation for guests must be trivial. If the remote stat and sensor (WIFI) fail, the box at th heater end must be able to keep heat within reaonable limits. The SALUScontrol we got with the system is utterly useless.

I'm coming to the conclusion I'll have to make my own stat - and ading Alexa overrides would be great.

**Comment by datech** [comment]
I see. Alexa is always a good addition :)

May we consider this issue as resolved?

**Comment by scargill** [comment]
Not resolved but not major.  As you add more devices to the hub, Alexa "find new devices" says no new devices - but they work (yes, in Alexa).

**Comment by datech** [comment]
Hm, this could be, because you have multiple devices in your network responding on Alexa SSDP messages or you have a large number of devices linked to the Amazon Echo Node. Discovery process should be completed for 20 sec and if it doesn't Alexa will report that "there are no new devices found".  Actually,  in the background, the process will continue and at the end, all new devices will be listed in the mobile app.

**Comment by scargill** [comment]
Thanks Datech  - that make sense as they DO work.
