### ISSUE TITLE
Add client IP address

### ISSUE THREAD

**Issue by hifiberry** [datech/node-red-contrib-amazon-echo#22]
It would be good to have the IP address of the Amazon Echo that sent the request in the JSON data. This would allow better automatisations with multiple Echo devices in the same apartment.

**Comment by Barabba11** [comment]
To let use the same names to different Echo devices (example soft lights in different rooms/floors) it would be better to specify IP address of the desidered Echo into Node Red Echo HUB, and connect to it the devices that we want only that Echo should recognize.

**Comment by hifiberry** [comment]
Not sure how you mean that. You mean during discovery? In this case this won't work as all Echo devices on the same account share the discovered devices.

**Comment by Barabba11** [comment]
Yes, and you can't use duplicate names, for example. If you "customize" the HUB for working only with that Echo you can be sure the JSON data will come from only that Alexa

**Comment by hifiberry** [comment]
That's not the idea here. I don't want to have multiple hubs. This would complicate things a lot. I want a single hub for all Alexa's. It should just be possible to identify which Alexa sent the command, that's all. A simple attribute with the IP address of the client would be enough for this.

**Comment by hifiberry** [comment]
Ok, I patched the code and added the client IP address. Bad news: requests always come from a "master" Alexa device in the network. Other Alexa devices route their requests via the master device. I don't know if there is any other way to identify the "active" Alexa device.

**Comment by Barabba11** [comment]
So you mean Alexa are descovering each other into the network and assign between them a master? That's a horrible news!

**Comment by hifiberry** [comment]
Seems like this. All the requests to the Hue emulation always come from a single Alexa device, even if you're talking to another device. 
I wouldn't say this is "horrible", but it won't allow an emulated Hue to behave differently for different Alexa devices.

**Comment by Barabba11** [comment]
are you maybe using the same amazon account for both Alexa? Have you tried to register the Alexas in different accounts?

**Comment by hifiberry** [comment]
Sure I'm using the same account. Setting them up on different accounts doesn't make sense to me.

**Comment by Barabba11** [comment]
PLease use a different account, and then check if the IP packet come from different IP, that maybe can make sense to you,.
