### ISSUE TITLE
My wife's account can't' see devices

### ISSUE THREAD

**Issue by purebenwoo** [datech/node-red-contrib-amazon-echo#25]
##### SUMMARY

We have two accounts using Echo - mine, and my wife's. While my account can see all the devices created, when I switch to my wife's account, it doesn't see any of the devices I created.

##### ECHO DEVICES

2x Echo Dot 2nd gen
1x Echo Dot 3rd gen

##### MODULE VERSION

```paste below
0.1.8
```

##### CONFIGURATION

```paste below
Amazon Echo Hub <-> Test node <-> mqtt output
```

##### CONSOLE OUTPUT

```paste below
`20 Feb 15:55:43 - [debug] [api-call-service:Foyer Light Off] instantiated node, name: Foyer Light Off
20 Feb 15:55:43 - [debug] [api-call-service:Unlock Front Door] instantiated node, name: Unlock Front Door
20 Feb 15:55:43 - [debug] [api-call-service:Den Lights On] instantiated node, name: Den Lights On
20 Feb 15:55:43 - [debug] [api-call-service:Den Lamp On] instantiated node, name: Den Lamp On
20 Feb 15:55:43 - [debug] [api-call-service:Den Lights Off] instantiated node, name: Den Lights Off
20 Feb 15:55:43 - [debug] [api-call-service:Den Lamp Off] instantiated node, name: Den Lamp Off
20 Feb 15:55:43 - [debug] [api-call-service:Bedroom On] instantiated node, name: Bedroom On
20 Feb 15:55:43 - [debug] [api-call-service:Mood Lighting On] instantiated node, name: Mood Lighting On
20 Feb 15:55:44 - [debug] [api-call-service:Bedroom Off] instantiated node, name: Bedroom Off
20 Feb 15:55:44 - [debug] [api-call-service:Mood Lighting Off] instantiated node, name: Mood Lighting Off
20 Feb 15:55:44 - [debug] [server-state-changed:Bedroom Switch] instantiated node, name: Bedroom Switch
20 Feb 15:55:44 - [debug] [server-state-changed:Kitchen Switch] instantiated node, name: Kitchen Switch
20 Feb 15:55:44 - [debug] [api-call-service:Kitchen Lights On] instantiated node, name: Kitchen Lights On
20 Feb 15:55:44 - [debug] [api-call-service:Kitchen Lights Off] instantiated node, name: Kitchen Lights Off
20 Feb 15:55:44 - [info] Started flows
20 Feb 15:55:44 - [info] [mqtt-broker:MQTT Broker] Connected to broker: mqtt://10.10.10.3:1883
20 Feb 15:55:44 - [info] [server:Home Assistant] WebSocket Connected to https://example.org
20 Feb 15:55:44 - [debug] [server:Home Assistant] config server event listener connected
20 Feb 16:10:45 - [info] Uninstalling module: node-red-contrib-alexa-local
20 Feb 16:11:43 - [info] Uninstalled module: node-red-contrib-alexa-local
20 Feb 16:11:43 - [info] Removed node types:
20 Feb 16:11:43 - [info]  - node-red-contrib-alexa-local:alexa-local
20 Feb 16:11:48 - [info] [server:Home Assistant] WebSocket Closed https://example.org
20 Feb 16:11:48 - [debug] [server:Home Assistant] config server event listener closed
20 Feb 16:11:48 - [debug] [server:Home Assistant] WebSocket Connecting https://example.org
20 Feb 16:11:48 - [debug] [server:Home Assistant] config server event listener connecting
20 Feb 16:11:48 - [info] [server:Home Assistant] WebSocket Connected to https://example.org
20 Feb 16:11:48 - [debug] [server:Home Assistant] config server event listener connected
`
```

##### STEPS TO REPRODUCE

Alexa, discovery devices

##### EXPECTED RESULTS

Devices should show up in my wife's account

##### ACTUAL RESULTS

Nothing

**Comment by Barabba11** [comment]
I=?m not the author but it's strange, I tested with 2 Echos and the http server is always responsive, ssems your Echo doesn't really search on LAN when you using the wife account.
If I undersood right you're using the same device, and without touching it you're simply switch the account in your app, and you are sure your wife account is responsive in that Echo, for example yoiu can pair a bluetooth like the phone.. 
It's confusing because you talk about change account only, but you also report you have:
2x Echo Dot 2nd gen
1x Echo Dot 3rd gen

**Comment by purebenwoo** [comment]
Sorry it is confusing, let me see if I can clarify. All my echo dots are registered to me. I can discover the new "devices" that I have created using Amazon Echo Hub palette on Node RED. When I switch to my wife's account (either via asking Alexa to "switch accounts" OR using my wife's username/password on alexa.amazon.com) and ask it to discover, it discovers no devices.
On 2/20/2019 12:07:36 PM, Barabba11 <notifications@github.com> wrote:
I=?m not the author but it's strange, I tested with 2 Echos and the http server is always responsive, ssems your Echo doesn't really search on LAN when you using the wife account.
If I undersood right you're using the same device, and without touching it you're simply switch the account in your app, and you are sure your wife account is responsive in that Echo, for example yoiu can pair a bluetooth like the phone..
It's confusing because you talk about change account only, but you also report you have:
2x Echo Dot 2nd gen
1x Echo Dot 3rd gen

**Comment by Barabba11** [comment]
If you are sure you are not changing wifi. etc. maybe it is a protection of Amazon? To don't let 2 accounts discover the same devices? Alexa is connected to internt, so this is possible to do.. 
But in my case, with 3 3rd echo in the same wifi, different accounts, they were discovering the same devices.

**Comment by purebenwoo** [comment]
Hmm interesting thought. I have a 3td and a couple of 2nds.. I'll try again
to see
 Thanks for the input.

**Comment by purebenwoo** [comment]
OK, been trying all sorts of things, still no go. My account works, but when I switch to my wife's account, I can't find the devices anymore.

**Comment by datech** [comment]
@purebenwoo Sorry for the very late response

I've just verified it, and it looks like that this is a typical Alexa behavior. Smart home devices are not synchronized between household accounts. 

The solution is to ask Alexa to discover devices for each household account.
