### ISSUE TITLE
Identify specific echo device

### ISSUE THREAD

**Issue by zaphod2010** [datech/node-red-contrib-amazon-echo#26]
##### SUMMARY

Is it possible to distingush my echo devices somehow? is there a unique echo device ID which can be added to the payload?
##### MODULE VERSION

`0.1.8`

##### CONFIGURATION

```

##### CONSOLE OUTPUT
<!--- Paste Node-RED console output between quotes -->
```paste below

```

**Comment by Barabba11** [comment]
Well, I asked the same.. 
chances are Echo devices becoming cheaper, it would lovely to have other Echo in other rooms/floors.. but only one Wifi, and only one Raspberry running Node Red an all automations needed.. 
Unfortunately Echo will search for devices on port 80 on the IP domain broadcast.. so or we use multiple IP addresses on Raspberry and open for each IP an 80 (to be routed somehow to the main IP with a different TCP) or we've to try to chose/filter the Echo device on the http server (by its IP or MAC address) and let it recognize only the devices connected to it only.
Possible solution:
It may be possible to change a bit the http server to pass also the source IP address of the Echo device incoming, on Node red the Echo HUB device can contain a field to specify the Echo IP address, this HUB will talk only to that IP address, and let that Echo only recognize the devices connected to that Echo HUB. 
We ma add then a second Echo HUB with the IP address of the second Alexa, and connect to it only the devices that the second Alexa should recognize and control. 
A device may be connected to two hubs and be recognized and controlled by both.. but this is not mandatory of course
Thank you a lot for considering this

**Comment by datech** [comment]
I'm not aware of a way to distinguish Amazon Echo devices, because usually all requests are routed trough the master Echo device.

Duplicate issues #22 , #59

**Comment by Barabba11** [comment]
It's just needed to use two different Amazon accounts, one for every Echo.
Filter can be set on every device by IP address, hub will pass source IP address to device, if it doesn't match the device will not reply
Thank you
