### ISSUE TITLE
Alexa App is not getting status change update by mqtt

### ISSUE THREAD

**Issue by vijayvikma** [datech/node-red-contrib-amazon-echo#27]
Hello Experts,

I have used node-red-contrib-amazon-echo and it works like a charm in one way.

My device can be turned on/off by mqtt.

With this module its working with echo dot 3rd generation but when i change the status via mqtt,it is not reflecting in alexa app.

Please resolve the issue.
Thanks in advance.

![Untitled](https://user-images.githubusercontent.com/47443662/54191877-c92a5780-44dc-11e9-9651-8168b364c102.png)

**Comment by Barabba11** [comment]
I don't think this is possibile, if I understood right the author used an existing protocol to drive Philips lamps and imported on Node Red, shortly the Alexa think that Node Red it's a Philips lamp. This protocol don't include a bidirectional comunication, Alexa doesn't care to know the status of light and its intensity, for example. 
Ther author would need to find other "local devices" that may include this, it means devices already known and supported by Alexa, it may be interesting, but I don't know if possibile, and especially find a bidirectional one.
You may better feel oriented with Alexa skills, you need to open an account on internet and tell what Alexa should do there.. you may catch the status by mqtt and send to skills..

**Comment by vijayvikma** [comment]
@Barabba11 Thank you so much  for the quick reply.

**Comment by datech** [comment]
@vijayvikma I could try to implement something similar to this: https://github.com/datech/node-red-contrib-amazon-echo/wiki/Integration-with-Sonoff-Tasmota

**Comment by vijayvikma** [comment]
Thanks much.I will try that and update here.I tried this thing but i think did not write function properly.It should work fine with MQTT input node if it has subscribe to correct topic regardless of tasmota ?

**Comment by vijayvikma** [comment]
super cool.thats working.Many thanks to @datech

**Comment by ronny130286** [comment]
Hi, I have a similar problem.
I want to monitor a condition from an external surge switch. If send the state of the gpio to the hub, the status for the device is also set correctly. Unfortunately, the device sends a payload too and the surge switch turn off, can one prevent this?

**Comment by eartvit** [comment]
> @vijayvikma I could try to implement something similar to this: https://github.com/datech/node-red-contrib-amazon-echo/wiki/Integration-with-Sonoff-Tasmota

I tried this out and it works. Thank you for the suggestion (and thank you for writing this integration)

Is there a way to trick the Alexa app to display the device as a switch rather than a light?
