### ISSUE TITLE
Does it work with only Alexa App?

### ISSUE THREAD

**Issue by alexschwantes** [datech/node-red-contrib-amazon-echo#28]
##### SUMMARY
Will this work with just node red and the alexa app? 

I don't actually have an echo device but do have sonos one with alexa configured. I am unable to get it to find the devices from the alexa app. Have also tried asking alexa on the sonos to find devices without any luck..

##### ECHO DEVICES
Alexa app on phone and sonos one

##### MODULE VERSION
0.1.8
Node-RED version: v0.20.0
Node.js  version: v10.15.3

##### CONFIGURATION
just a basic hub connected to 1 device
I have it configured correctly on port 80, and can access http://192.168.1.201/description.xml

```
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.201:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Philips hue (192.168.1.201)</friendlyName>
<manufacturer>Royal Philips Electronics</manufacturer>
<manufacturerURL>http://www.philips.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2012</modelName>
<modelNumber>1000000000000</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>93eadbeef13</serialNumber>
<UDN>uuid:00112233-4455-6677-8899-a0e115acd0fc28</UDN>
<serviceList>
<service>
<serviceType>(null)</serviceType>
<serviceId>(null)</serviceId>
<controlURL>(null)</controlURL>
<eventSubURL>(null)</eventSubURL>
<SCPDURL>(null)</SCPDURL>
</service>
</serviceList>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<height>120</height>
<width>120</width>
<depth>24</depth>
<url>hue_logo_3.png</url>
</icon>
</iconList>
</device>
</root>
```

**Comment by Barabba11** [comment]
I have no idea of the app you're trying, this module creates a web server on port 80 where Echo can find out and recognize as a Philps light (if I?m not wrong). To start the search progress is enough to tell to Echo "Alexa, find new devices".
I don't know if the app you're using will scan the IP domain and look for devices..

**Comment by alexschwantes** [comment]
The app is the official Alexa app. You can say "find my devices" or do it via the app menu and it looks for devices via the app/wifi network on your mobile phone. This is how it found the sonos speakers. However it never seems to find the webserver on port 80...

**Comment by alexschwantes** [comment]
So a little update, the answer is No. I bought an echo dot and connected it and then did 'discover devices' and it found the configured device without making any changes to the configuration. 

Its good to know that you actually need a physical echo device in order to use this, and that a Sonos speaker with Alexa configured on it or the Alexa app on the phone is not enough.
