### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by vajonam** [datech/node-red-contrib-amazon-echo#29]
Great work on a non cloud solution for echo and node integration. 

I would like control devices like garage doors etc, is possible to add I intents like open and close? Or because your are using hue emulator only the hue based intents are available?

**Comment by datech** [comment]
You can control any device, but using "turn off/on" Alexa commands. I haven't found a way to use **Open**/**Close** commands for example, without using Alexa skills. As for now, only Hue emulated devices are supported.

**Comment by vajonam** [comment]
Yes got it thanks.
