### ISSUE TITLE
How to use echo hub node in multiple flows

### ISSUE THREAD

**Issue by vijayvikma** [datech/node-red-contrib-amazon-echo#30]
Hello Experts,

I have echo 3rd generation.This module works perfectly fine  with 3rd generation echo on port 80.

The issue is i am not able to use the echo hub node in different flow.Can some please provide some trick on how we can use echo hub node in multiple flows.

if i copy and paste in different flow,it will not run on port 80 since already used.
If i change port to other then 80,then not able to send any thing.
even if i create subflow as a single node,its giving error.

**Comment by datech** [comment]
Hello,

You may try using links to connect the flows. It will work for this module also.

**Comment by vijayvikma** [comment]
@datech Thanks for the suggestion.I will give it a try and update here.
