### ISSUE TITLE
problem  with 0.1.8

### ISSUE THREAD

**Issue by artexx** [datech/node-red-contrib-amazon-echo#32]
##### SUMMARY
from today my flow is not working in nodered 
SyntaxError: Unexpected token * (line:371)
nodered 0.19.3
I have tried to remove and reinstall ma the problem is always there

##### MODULE VERSION

```paste below

```

##### CONFIGURATION

``

[
    {
        "id": "fa2662cf.760128",
        "type": "tab",
        "label": "ALEXA",
        "disabled": false,
        "info": ""
    },
    {
        "id": "3d21a2a0.332f36",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_luce_studio_1",
        "links": [
            "9959746b.fa85b"
        ],
        "x": 535,
        "y": 260,
        "wires": []
    },
    {
        "id": "7b5a58a0.493538",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_luce_studio_2",
        "links": [
            "cc076b79.cf814"
        ],
        "x": 535,
        "y": 300,
        "wires": []
    },
    {
        "id": "e294c2ce.ff2b58",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_cameretta_1",
        "links": [
            "7f024cd1.d7a6ac"
        ],
        "x": 535,
        "y": 20,
        "wires": []
    },
    {
        "id": "623e677c.3bbdb",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_cameretta_2",
        "links": [
            "b4c33732.3686b"
        ],
        "x": 535,
        "y": 60,
        "wires": []
    },
    {
        "id": "182e7533.7e630b",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_cameretta_3",
        "links": [
            "3d8296a6.0ead0a"
        ],
        "x": 535,
        "y": 100,
        "wires": []
    },
    {
        "id": "f6b259e8.b0d81",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_camera_1",
        "links": [
            "beed99d3.cc81b8"
        ],
        "x": 535,
        "y": 140,
        "wires": []
    },
    {
        "id": "71ae196e.079cb",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_camera_2",
        "links": [
            "532802ab.c0ff3c"
        ],
        "x": 535,
        "y": 180,
        "wires": []
    },
    {
        "id": "70a4c02d.37bf28",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_camera_3",
        "links": [
            "8abdcc2.4173db"
        ],
        "x": 535,
        "y": 220,
        "wires": []
    },
    {
        "id": "372bb325.6210ac",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_corridoio_1",
        "links": [
            "6d020787.7d5c6"
        ],
        "x": 535,
        "y": 340,
        "wires": []
    },
    {
        "id": "d18f45a6.854d48",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_corridoio_2",
        "links": [
            "de547166.d59b4"
        ],
        "x": 535,
        "y": 380,
        "wires": []
    },
    {
        "id": "269f532e.9a46fc",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_luce_strada",
        "links": [
            "6b39221f.73ed7c"
        ],
        "x": 535,
        "y": 420,
        "wires": []
    },
    {
        "id": "b045cc60.6a11d",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_luce_balcone",
        "links": [
            "44c8f1a3.fa21a8"
        ],
        "x": 535,
        "y": 460,
        "wires": []
    },
    {
        "id": "1098966f.1a3d52",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_bagno_1",
        "links": [
            "e4114386.b89fc"
        ],
        "x": 535,
        "y": 500,
        "wires": []
    },
    {
        "id": "4fe3e7b9.95f53",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_bagno_2",
        "links": [
            "bbd0a7a5.0c9428"
        ],
        "x": 535,
        "y": 540,
        "wires": []
    },
    {
        "id": "868400ad.98b7f8",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_bagno_3",
        "links": [
            "943fd243.7575b8"
        ],
        "x": 535,
        "y": 580,
        "wires": []
    },
    {
        "id": "4f6d2a22.0e4934",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_sala_1",
        "links": [
            "417dd743.dd18d8"
        ],
        "x": 535,
        "y": 620,
        "wires": []
    },
    {
        "id": "96e02c22.51863",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_sala_2",
        "links": [
            "34d0bd10.bdc052"
        ],
        "x": 535,
        "y": 660,
        "wires": []
    },
    {
        "id": "37ff4315.53325c",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_sala_3",
        "links": [
            "8d503d34.0d02b"
        ],
        "x": 535,
        "y": 700,
        "wires": []
    },
    {
        "id": "916ec9d2.ff3518",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_bagnetto_1",
        "links": [
            "f9b8139.89342f"
        ],
        "x": 535,
        "y": 740,
        "wires": []
    },
    {
        "id": "d3476820.214a1",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_bagnetto_2",
        "links": [
            "fb48c3f5.4a29e8"
        ],
        "x": 535,
        "y": 780,
        "wires": []
    },
    {
        "id": "18366cb3.58a1db",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_cucina_1",
        "links": [
            "d5f25b4c.c9f308"
        ],
        "x": 535,
        "y": 820,
        "wires": []
    },
    {
        "id": "38385f2f.bb1bf8",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_cucina_2",
        "links": [
            "42d5d69a.7f032"
        ],
        "x": 535,
        "y": 860,
        "wires": []
    },
    {
        "id": "c3de2a67.9425a8",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_cucina_3",
        "links": [
            "483aeaf2.ec5ab4"
        ],
        "x": 535,
        "y": 900,
        "wires": []
    },
    {
        "id": "741fe62b.6cd15",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_ingresso",
        "links": [
            "b95f2c12.458ce"
        ],
        "x": 535,
        "y": 940,
        "wires": []
    },
    {
        "id": "e3bc0db1.a790d8",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_scale",
        "links": [
            "c02f2e57.eea2d8"
        ],
        "x": 535,
        "y": 980,
        "wires": []
    },
    {
        "id": "c4943f3b.0d45c8",
        "type": "link out",
        "z": "fa2662cf.760128",
        "name": "to_riscaldamenti",
        "links": [
            "abba8c95.595908"
        ],
        "x": 535,
        "y": 1020,
        "wires": []
    },
    {
        "id": "46cbd476.a683dc",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce studio 1",
        "topic": "",
        "x": 390,
        "y": 260,
        "wires": [
            [
                "3d21a2a0.332f36"
            ]
        ]
    },
    {
        "id": "764eb742.9db1c",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce studio 2",
        "topic": "",
        "x": 390,
        "y": 300,
        "wires": [
            [
                "7b5a58a0.493538"
            ]
        ]
    },
    {
        "id": "376fa610.ec59d2",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce cameretta 1",
        "topic": "",
        "x": 400,
        "y": 20,
        "wires": [
            [
                "e294c2ce.ff2b58"
            ]
        ]
    },
    {
        "id": "8acc1822.b5a218",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce cameretta 2",
        "topic": "",
        "x": 400,
        "y": 60,
        "wires": [
            [
                "623e677c.3bbdb"
            ]
        ]
    },
    {
        "id": "591e1a96.3be784",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce cameretta 3",
        "topic": "",
        "x": 400,
        "y": 100,
        "wires": [
            [
                "182e7533.7e630b"
            ]
        ]
    },
    {
        "id": "25126a83.d253ee",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce camera 1",
        "topic": "",
        "x": 400,
        "y": 140,
        "wires": [
            [
                "f6b259e8.b0d81"
            ]
        ]
    },
    {
        "id": "ac472957.d70ca8",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce camera 2",
        "topic": "",
        "x": 400,
        "y": 180,
        "wires": [
            [
                "71ae196e.079cb"
            ]
        ]
    },
    {
        "id": "c12e0ba8.cdcf5",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce camera 3",
        "topic": "",
        "x": 400,
        "y": 220,
        "wires": [
            [
                "70a4c02d.37bf28"
            ]
        ]
    },
    {
        "id": "47f6c3d3.856e94",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce corridoio 1",
        "topic": "",
        "x": 400,
        "y": 340,
        "wires": [
            [
                "372bb325.6210ac"
            ]
        ]
    },
    {
        "id": "d9809251.3dd828",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce corridoio 2",
        "topic": "",
        "x": 400,
        "y": 380,
        "wires": [
            [
                "d18f45a6.854d48"
            ]
        ]
    },
    {
        "id": "1c4187a2.46751",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce strada",
        "topic": "",
        "x": 390,
        "y": 420,
        "wires": [
            [
                "269f532e.9a46fc"
            ]
        ]
    },
    {
        "id": "1c71b4d2.13911b",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce balcone",
        "topic": "",
        "x": 390,
        "y": 460,
        "wires": [
            [
                "b045cc60.6a11d"
            ]
        ]
    },
    {
        "id": "8f555505.5146f",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce bagno 1",
        "topic": "",
        "x": 390,
        "y": 500,
        "wires": [
            [
                "1098966f.1a3d52"
            ]
        ]
    },
    {
        "id": "8f6d9489.c2fc78",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce bagno 2",
        "topic": "",
        "x": 390,
        "y": 540,
        "wires": [
            [
                "4fe3e7b9.95f53"
            ]
        ]
    },
    {
        "id": "43ec1bf8.2add9c",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce bagno 3",
        "topic": "",
        "x": 390,
        "y": 580,
        "wires": [
            [
                "868400ad.98b7f8"
            ]
        ]
    },
    {
        "id": "784c62dc.87bd4c",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce sala 1",
        "topic": "",
        "x": 390,
        "y": 620,
        "wires": [
            [
                "4f6d2a22.0e4934"
            ]
        ]
    },
    {
        "id": "2f933925.113566",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce sala 2",
        "topic": "",
        "x": 390,
        "y": 660,
        "wires": [
            [
                "96e02c22.51863"
            ]
        ]
    },
    {
        "id": "286149ce.d356de",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce sala 3",
        "topic": "",
        "x": 390,
        "y": 700,
        "wires": [
            [
                "37ff4315.53325c"
            ]
        ]
    },
    {
        "id": "264f0c9.3008674",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce bagnetto 1",
        "topic": "",
        "x": 400,
        "y": 740,
        "wires": [
            [
                "916ec9d2.ff3518"
            ]
        ]
    },
    {
        "id": "7c34a52.7cdaa5c",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce bagnetto 2",
        "topic": "",
        "x": 400,
        "y": 780,
        "wires": [
            [
                "d3476820.214a1"
            ]
        ]
    },
    {
        "id": "c782295.c632d58",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce cucina 1",
        "topic": "",
        "x": 390,
        "y": 820,
        "wires": [
            [
                "18366cb3.58a1db"
            ]
        ]
    },
    {
        "id": "67265c5b.e25fc4",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce cucina 2",
        "topic": "",
        "x": 390,
        "y": 860,
        "wires": [
            [
                "38385f2f.bb1bf8"
            ]
        ]
    },
    {
        "id": "c6153a3c.1155a",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce cucina 3",
        "topic": "",
        "x": 390,
        "y": 900,
        "wires": [
            [
                "c3de2a67.9425a8"
            ]
        ]
    },
    {
        "id": "b0e6c940.3b9058",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce ingresso",
        "topic": "",
        "x": 400,
        "y": 940,
        "wires": [
            [
                "741fe62b.6cd15"
            ]
        ]
    },
    {
        "id": "27061a57.7cd3e6",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "luce scale",
        "topic": "",
        "x": 390,
        "y": 980,
        "wires": [
            [
                "e3bc0db1.a790d8"
            ]
        ]
    },
    {
        "id": "a6ebdd1c.d1efe8",
        "type": "amazon-echo-device",
        "z": "fa2662cf.760128",
        "name": "riscaldamenti",
        "topic": "",
        "x": 400,
        "y": 1020,
        "wires": [
            [
                "c4943f3b.0d45c8"
            ]
        ]
    },
    {
        "id": "10156656.cfab62",
        "type": "amazon-echo-hub",
        "z": "fa2662cf.760128",
        "port": "80",
        "enableinput": false,
        "x": 130,
        "y": 200,
        "wires": [
            [
                "376fa610.ec59d2",
                "8acc1822.b5a218",
                "591e1a96.3be784",
                "25126a83.d253ee",
                "ac472957.d70ca8",
                "c12e0ba8.cdcf5",
                "46cbd476.a683dc",
                "764eb742.9db1c",
                "47f6c3d3.856e94",
                "d9809251.3dd828",
                "1c4187a2.46751",
                "1c71b4d2.13911b",
                "8f555505.5146f",
                "8f6d9489.c2fc78",
                "43ec1bf8.2add9c",
                "784c62dc.87bd4c",
                "2f933925.113566",
                "286149ce.d356de",
                "264f0c9.3008674",
                "7c34a52.7cdaa5c",
                "c782295.c632d58",
                "67265c5b.e25fc4",
                "c6153a3c.1155a",
                "b0e6c940.3b9058",
                "27061a57.7cd3e6",
                "a6ebdd1c.d1efe8"
            ]
        ]
    }
]
```

##### CONSOLE OUTPUT
<!--- Paste Node-RED console output between quotes -->
```
Flows stopped due to missing node types.

    amazon-echo-hub

```

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->

##### ACTUAL RESULTS
<!--- Describe what actually happened. -->

**Comment by datech** [comment]
@artexx Have you resolved this?

**Comment by artexx** [comment]
Solved only reinstalling everything


Il mer 25 set 2019, 21:56 Teodor Ivanov <notifications@github.com> ha
scritto:

**Comment by Nakedape** [comment]
Sorry to necro, but I also am having this issue. Several, remove/reinstalls didn't seem to fix it.
Running on a rpi. I tried updating/upgrading and reinstalling. Same issue.

Nodes seem to be installed and upon browser refresh do not show. and are grayed out in the pallet manager.

4 Oct 21:31:19 - [info]  - node-red-contrib-amazon-echo:amazon-echo-hub : SyntaxError: Unexpected token ... (line:371)
4 Oct 21:31:19 - [info]  - node-red-contrib-amazon-echo:amazon-echo-device : SyntaxError: Unexpected token ... (line:371)

Above is from the node-red-log when I install via pallet. I tried npm install...it didn't seem to add anything to the pallet.

Thanks.

**Comment by Barabba11** [comment]
Are you running the new NR 1.0?
Are you running NR/and installed it from the user account, and not the root account? This is crucial, if you did from root then remove all and reinstall all.

**Comment by Nakedape** [comment]
I'm on 0.17.4 and I couldn't tell you how NR was installed bc it was so long ago. :/ but it's likely that it was indeed from root.

(I did try from the module first and command line when that didn't work.)

Never the less,
This pi setup is so old now, I will likely wipe the pi and fresh install to NR 1.0 when I get a chance.
Thanks for the help. :+1:
