### ISSUE TITLE
Not Working Echodot 3rd Generation

### ISSUE THREAD

**Issue by ceaswaran** [datech/node-red-contrib-amazon-echo#36]
##### SUMMARY

I am using Amazon Alexa Echo dot 3rd Gen
currently running Home Assistant 0.91.3 (hass.io) on Raspberry Pi
Using NodeRed addon (currently running version 2.0.2) on Hassio 
The wiki page says "No additional settings are needed if Node-Red is started as Home Assistant add-on"

My Echo dot doesn't recognize any new devices after discovery, no debug report as well.

Please help

##### ECHO DEVICES

Amazon Echo dot 3rd Gen

##### MODULE VERSION

```paste below
node-red-contrib-amazon-echo
0.1.8
```

##### CONFIGURATION

```paste below
[{"id":"c15f854f.0a7688","type":"amazon-echo-hub","z":"64e1b166.51d91","port":"80","enableinput":false,"x":166,"y":195,"wires":[["4756b904.76b378","722ecd05.ebc714"]]},{"id":"4756b904.76b378","type":"amazon-echo-device","z":"64e1b166.51d91","name":"Laptop","topic":"","x":356,"y":154,"wires":[["1cd9a957.3c2427"]]},{"id":"722ecd05.ebc714","type":"debug","z":"64e1b166.51d91","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":396,"y":265,"wires":[]},{"id":"1cd9a957.3c2427","type":"debug","z":"64e1b166.51d91","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":687,"y":191,"wires":[]}]
```

##### CONSOLE OUTPUT

```paste below

```

**Comment by Barabba11** [comment]
I had a similar problem (but it happened once, after months, with more then 60 devices), does Alexa replies on discovery command with a sound (not a voice!) of "falied to do" or refuse?
If so I fixed going to Amazon Alexa account, remove all devices, press the button on Alexa to go to config mode, from phone app unregister Alexa, wait a minute, add it again, discover devices worked. You will not loose any preference I guess

**Comment by ceaswaran** [comment]
@Barabba11 My Echodot say "No New devices Discovered"

**Comment by Barabba11** [comment]
be careful to have connected the devices to the hub, once I forgot and it didn't recognize. The other devices work? It meand the http server is listening to port 80 and replying to Alexa

**Comment by ceaswaran** [comment]
All other devices connected thru cloud with respective skill to Alexa works well (Example Tuya devices that are connected thru tuya skill works fine)
but local devices don't work with this node, please help
Am I missing something?

**Comment by Barabba11** [comment]
Yes, you for sure are facing the lock of port 80 in your raspberry, look around closed issues how to nat the port 80 on one higher than 1024

**Comment by ceaswaran** [comment]
sorry to ask again since am not an expert in this field. @Barabba11
 I run Nodered as Addon on my hassio . The wiki for this node says
"No additional settings are needed if Node-Red is started as Home Assistant add-on". 
How do i unlock port 80 on my raspberry.  Please help

**Comment by Barabba11** [comment]
Pe patient and read yourself the closed issues to understand how this is working, follow my suggestions here for example. There are different people that experienced your problem, so it's common. Echo search for devices with port 80 opened, Rasperry without cannot open ports lower thank 1024
https://github.com/datech/node-red-contrib-amazon-echo/issues/5#issuecomment-456573898

**Comment by ceaswaran** [comment]
@Barabba11  i read those comments
I am running Hassio on Raspberry pi 2, as far as I know, this setup doesn't have a terminal or SSH option to connect

hence my query on how can I change the listening port from 80 to 8000

Please help

**Comment by ceaswaran** [comment]
i see the port 80 is open in my hassio (Rapberry pi ) thru fing app as follows

```
IP Address: 192.1XX.X.XX
State: Online
MAC: XX:XX:XX:XX:XX:XX
Vendor: Raspberry Pi
NetBIOS name: XXXXXX
NetBIOS role: [FILE SERVER]
Bonjour name: hassioXXXXXX
First seen: Thursday 21 March 19, 6:47 am
Last change: Thursday 4 April 19, 8:18 am

Active services: X
	80/http World Wide Web HTTP
```

**Comment by Barabba11** [comment]
Be sure you don't have other services that opened already the 80, if so you need to kill them or change their port. Alexa talk only with 80, point.
Put on hub server any you like, but free! I use 8008. Then use nat commands.
You should find a way to activate SSH, or telnet, or use mouse keyboard and monitor on hdmi

**Comment by ceaswaran** [comment]
@Barabba11 I got it working
I uninstalled & reinstalled the echo node in Node Red.
It started to discover the devices. though really don't know what was going wrong
