### ISSUE TITLE
If I import a flow (for example backup) Alexa will not control more devices

### ISSUE THREAD

**Issue by Barabba11** [datech/node-red-contrib-amazon-echo#38]
Hi, for the first time on my NR I had to clear all flows and restore the latest backup (export- clipboard - all flows), all was working exept this modules and the reason I believe is because during the Alexa searching the module send to it the node number that NR create for every device, and when I create a new flow NR will assign new numbers to nodes, different ones. I checked that Alexa sent to HUB the proper message (I've logged it) but the HUB can't more redirect it to the proper device, message is lost. I should remove all Alexa devices (better to reset Alexa completely) and search again for all devices.

Of course with this method we can't export the flow and restore it easy as we should suppose to do, so I would suggest to add on devices proprieties a manual ID field, which can be precompiled with the ID that NR created for that node, so the user don't have to define it. In this way these infos can be exported on the clipboard and restored automatically on the backup. 
At this moment the only solution to restore flows 100% seems to backup the flows_raspberrypi.json file and restore it

**Comment by datech** [comment]
It is because node UUIDs are used to identify the devices that will be controlled by Amazon Echo Hub

**Comment by Barabba11** [comment]
There is a way to solve this? As Vernus introduced names, and if I remember right I read somewhere you too, there are chances to give a device an unique node, that can be sent to Echo as device ID, and can be restored with import? (And Echo that remembers that will keep working with same device)
Thank you!

**Comment by datech** [comment]
#115 is suggesting how to implement it.
