### ISSUE TITLE
Which element to identify its activation comes from to prevent input pasthrough

### ISSUE THREAD

**Issue by wongnam** [datech/node-red-contrib-amazon-echo#39]
I have just want to know which element to identify its activation comes from to prevent input pasthrough
eg: to prevent input passthrough if the trigger from input node, of course
it will send the command if the trigger is from Alexa.

![image](https://user-images.githubusercontent.com/36041520/57594141-df01da80-7568-11e9-9094-48032a7b70e4.png)

for example:  
- in node-red-contrib-alexa-local i detect the topic is null or not to prevent input pass through.
![image](https://user-images.githubusercontent.com/36041520/57594525-bf6bb180-756a-11e9-9c3a-14ac2df106e7.png)

- in node-red-contrib-homekit I detect the msg.hap.context is null or not to prevent input pass through.
![image](https://user-images.githubusercontent.com/36041520/57594370-ed9cc180-7569-11e9-8815-84e97090e62e.png)

**Comment by dermm** [comment]
Hi wongman!
I had semilar problems and decided me to break the passtrough. The Input on the Node is only serves updates the status in Alexa.
Her my fork https://github.com/dermm/node-red-contrib-amazon-echo
If you see the lines that have been changed, you could change it so that it is still passed through with an addition in the payload.

**Comment by Barabba11** [comment]
Hi dermm, thank you for the kind post and really welcome contribute! 
Since the author here is not more present (we hope one day to see him back!) are you interested to keep developing his module?
Thank you

**Comment by wongnam** [comment]
> Hi wongman!
> I had semilar problems and decided me to break the passtrough. The Input on the Node is only serves updates the status in Alexa.
> Her my fork https://github.com/dermm/node-red-contrib-amazon-echo
> If you see the lines that have been changed, you could change it so that it is still passed through with an addition in the payload.

Thanks @dermm Good news. Let me try it now.

**Comment by wongnam** [comment]
@dermm how to install your it on my Node-red?

**Comment by wongnam** [comment]
@dermm It worked very well, good job. Thanks.
@datech appreciate if you merge this function to you code to improve the using experience.

Thanks.

**Comment by jgaret** [comment]
Hello, how did you manage to modify the files ? 
If I do so in my node module, when I restart node red it states that the amazon echo nodes are not recognized. 
Is there a command to update something to make it work ?

**Comment by wongnam** [comment]
Just replace 2 files then node-red-stop and node-red-start
![image](https://user-images.githubusercontent.com/36041520/58866455-d40f1580-86e2-11e9-9fee-97b1efe375f1.png)

**Comment by datech** [comment]
@wongnam, @dermm Can you confirm that #60 will resolve this?

**Comment by wongnam** [comment]
@datech Hi, I am afraid that I cannot check this button right now. I no longer use this button because it won't handle all my devices if it has more than 20 units.
BTW, Thank for the node.

**Comment by Barabba11** [comment]
I guess it's a big of echo, maybe you created names of devices too similar each other. Try to give short unique name, remove.all devices from Amazon account, remove echo from Amazon account, reset echo to factory, add it again and rediscover devices

**Comment by datech** [comment]
@wongnam, thanks for the info, I will close the issue then.

BTW, I've just done a test with 70 devices which my Echo Dot 3 managed to discover.

<img src="https://user-images.githubusercontent.com/535026/65722391-d7c11080-e0b4-11e9-8384-69602663de99.png" width="200"/>
