### ISSUE TITLE
How to update current state of "light"

### ISSUE THREAD

**Issue by gyanez91** [datech/node-red-contrib-amazon-echo#42]
Hi, sorry for put this here, but i don't find info about it, i added a TV as light on echo node work great on and off , but i have  a question, my tv also turn on or off with others ways, how can update the current status of the device on alexa light??, i think is by the input part of the node, but i don't know how, thanks and sorry :)

##### ECHO DEVICES
* Echo Dot Third Gen

**Comment by verjus** [comment]
You have to send a json payload describing the state you want to update to the input node "Amazon Echo Hub" (make sure you enabled input in the configuration of the node). The payload needs to also contain the nodeid of the device you want to update. To test this, use an "Inject Note" connected to the input node of the hub and select the JSON format for the payload to be injected. Type something like this: {"on":true, "bri":11, "nodeid": "<nodeid>"} for the payload, where <nodeid> is the ID of the node you want to update. To find the <nodeid> of your device look, use a Debug Node and search for nodeid value. 

Note that the way the author has implemented it may not suit your needs. In its current implementation, the system compares the current state it holds in memory with the state you send in the input node. If the state differs (e.g. brightness is different), the state is updated with the state in the payload (which is what you are asking) but a message is also triggered to the output node with the new state (which may not be always desired). I and others have modified this behavior (as well as other things in a fork) to make it optional.

**Comment by datech** [comment]
@verjus already mentioned that to update the status you could send an input payload to Amazon Echo Hub node

**Comment by david883** [comment]
I also have a device where I want to share the status with the hub.
But it does not work.

- I got the node is via the debug node.

- I connected the Incect to the Hub Input and entered the values.
Where do I make a mistake?

![IMG_20200710_125152](https://user-images.githubusercontent.com/28392840/87149813-386eb200-c2b1-11ea-825f-567932f89977.jpg)

![IMG_20200710_125241](https://user-images.githubusercontent.com/28392840/87149821-3f95c000-c2b1-11ea-8ddc-2ce59711ba20.jpg)

![IMG_20200710_125227](https://user-images.githubusercontent.com/28392840/87149836-458ba100-c2b1-11ea-8934-707a8f5d901a.jpg)

![IMG_20200710_125145](https://user-images.githubusercontent.com/28392840/87149843-4ae8eb80-c2b1-11ea-91bb-e8f289f31742.jpg)
