### ISSUE TITLE
Echo plus 2 can't discover devices

### ISSUE THREAD

**Issue by Dakyne** [datech/node-red-contrib-amazon-echo#48]
##### SUMMARY

I have an echo plus 2, and node red running as a home assistant add-on, and home assistant (hassos) is running in a vm.
My echo was able to detect a device once but that's all. I tried to reboot everything, reinstalling node-red skill and node-red-contrib-amazon-echo, but it's still not working.

##### ECHO DEVICES

* Echo Plus 2nd generation 

##### MODULE VERSION

```paste below
0.1.8
```

##### CONFIGURATION

```paste below
[{"id":"1a9e52f1.859305","type":"amazon-echo-hub","z":"772fd114.894fe","port":"80","enableinput":false,"x":140,"y":1060,"wires":[["df5c8add.55845"]]},{"id":"df5c8add.55845","type":"amazon-echo-device","z":"772fd114.894fe","name":"Ceiling light","topic":"","x":330,"y":1060,"wires":[["eef33af4.de4378"]]},{"id":"eef33af4.de4378","type":"debug","z":"772fd114.894fe","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":490,"y":1060,"wires":[]}]
```

##### CONSOLE OUTPUT

```paste below
No output
```

##### STEPS TO REPRODUCE

Use the minimal requirement for this to work and echo plus 2.
##### EXPECTED RESULTS

Being able to connect echo to nodes.
##### ACTUAL RESULTS

Echo plus discovers nothing.

**Comment by Barabba11** [comment]
Have you tried to remove Echo from your Amazon account, reset it after pushing the config button on Alexa as long it says "I'm resetting" (or something like that) and then discover again all devices?

**Comment by Dakyne** [comment]
I uninstalled everything and installed nodered as standalone and it works now. So it's not fixed, but it works ^^

**Comment by Barabba11** [comment]
As I had similar problems with Echo2 plus recently (unless one year ago, where it never fails to discover devices) there may be possible something change in new firmwares, there may be possible the answer this mod provide to Echo gives to echo some problems. Maybe it's not the protocol itself but the huge quantity of answer the Raspberry 3 can generate much faster then expected, causing the Echo to react unexpected.  More specifically I adviced the devices are not recognized within the expected "45 seconds" but some start working only after 2-3, or 5 or 10 minutes, before they are undiscovered, and after the process Alexa isn't more able to search for devices, it returns a "refuse sound", even after days. THe only chance to discover new devices is the reset Alexa (clear devices in account, remove echo from amazon account and reset echo). Chances are I'm using couple of words for some devices and the same first word, or maybe too many packets coming in a while of all the 50 devices. 
How fast HUB sending all devices? There is possible to introduce a small delay, like 200ms before sending the next device? It may solve some issues. Thank you!
