### ISSUE TITLE
Devices are always recognized as lights

### ISSUE THREAD

**Issue by averri** [datech/node-red-contrib-amazon-echo#50]
I think there is a design fault in this project: the devices are always recognized as lights! 

The data structure created for receiving commands for Alexa is great for controlling lights, but it does not apply for all other devices. What if I want to add a fan? It does not have RGB data. It would be great if we could specify the type of the device.

**Comment by tt2g89** [comment]
Hi @averri: As this node emulates a hue light hub and hue bulbs, the functionality is limited her. But you can theoretically also turn on or off a fan.

**Comment by Barabba11** [comment]
Correct, this limitation can't be overcome, as it emulates exactly a bulb (protocol copied). Anyway that's enough for us.. it would be better if the author may intruduce essential functions too,

**Comment by datech** [comment]
@averri can you elaborate more on how you can benefit from having diffrent device types?

**Comment by Barabba11** [comment]
Probably a different icon on the Alexa app on his phone. It can be also different commands, like close shutters instead of switch off shutters

**Comment by datech** [comment]
Duplicate to #34
