### ISSUE TITLE
Can this work with an AVS device?

### ISSUE THREAD

**Issue by Andergraw** [datech/node-red-contrib-amazon-echo#53]
First of all, thank you for your work! 
Now my question: I have been working on a RPi AVS enabled device (with official SDK) and after a lot of headaches, I discovered that neither this nor other LAN addons work with my device unless a real Alexa device is on and in the same LAN.
Would it be possible to make this plugin work locally, without linking to any Alexa skiil and with my Raspberry Pi with Alexa SDK on it?

Thanks,

**Comment by datech** [comment]
This module is simulating Phillips Hue hub and bulbs, so I suppose it will work.
I haven't tested it, but based on this blog post, Hue devices can be controlled by AVS.

https://developer.amazon.com/blogs/alexa/post/Tx1Y9P627EIYMTN/you-can-now-voice-control-philips-hue-devices-with-the-alexa-voice-service

Do you experience any issues?

**Comment by Andergraw** [comment]
Thanks for answering, datech.
Yes, my issue is, as explained, my RPi with Alexa SDK installed on it only responds to your Node-RED module if there is a real Alexa device present in the same LAN. The moment I try to use only my RPi, it doesn't work (unable to connect to service or provider is the message).
As stated, it happens exactly the same with other Hue LAN emulators (in the end we had to use the module that uses a skill and a cloud service).
Thanks!

**Comment by datech** [comment]
Just out of curiosity, have you tried to control the devices after they are already discovered, by adding a hardware Alexa device? I'm wondering if the problem is only the discovery process or it is not working at all.

One more suggestion - can you try to run the AVS and Node Red on the same box, docker container, VM or Pi (not sure how you've set it up). It has to eliminate all possible SSDP issues.

**Comment by Andergraw** [comment]
Yes, that was the way I discovered it wasn't working. We set everything up in our studio and sent the prototype to a place with no real Alexas. It never worked again (and it was working flawlessly here).
And...yes, everything was working in the same RPi. Node-RED server and Alexa SDK.
Thanks for your help!
