### ISSUE TITLE
Features needed, thanks

### ISSUE THREAD

**Issue by Barabba11** [datech/node-red-contrib-amazon-echo#54]
Hi datech and all peole may contribute here, 
it's long time this module isn't updated and I hope it can be soon. I have notenough knowledge to implement this changes myself, I'm asking help. Thank you.
Please report briefly your one, so maybe we can collect all here

1) Return a different object if the simple switch on or the intensity is given. I've read somewhere that in the packet Alexa sent it is possible to distinguish, it's very important for my project because I want to preserve the actual condition, that may be selected by wall buttons, and not by Node Red.
2) Associate a specific device to a particular Echo device (by IP address for exaple, or MAC) only that Echo will comunicate with that device and discover it, in this way we can have one Node red but different Echoes, and give the same names for every floor. "Alexa switch on the light" told in the second floor will not switch on the light of the first floor
3) chance to manually edit the ID of nodes or at least save it in the flow export, in this way if we restore the flow from the backup we don't have to discover again all devices by Alexa (a new flow will create new IDs, which Echo should not know). 
4) Unfortunately new Alexa firmware create some issues while discover devices, it may return a "failure" sound or discover devices after different minutes. Maybe not catch all active devices too. So maybe it's needed to improve compatibily to new Echo firmwares, in the past there weren't those problems I'm sure, but now maybe Echo became more strict how the device is answering it when discovering to avoid clones.. maybe hub return Echo too shortly a big quantity of informations at same time, maybe a bug in protocol, ect.

Thank you a lot for kind support!!

**Comment by Barabba11** [comment]
About point 1, there is already a solution here: https://github.com/verjus/node-red-contrib-amazon-echo

Anyone interested to help on other points? Thank you so much!

**Comment by datech** [comment]
@Barabba11 

1. and 2. were implemented as part of #67 and released in v0.1.9
3. #60 introduces the support of device names on input payload instead of device IDs. Released in v0.1.9 
4. Amazon increased the discovery timeout from 20 to 45 s, and we are not experiencing such issues now

BTW, it is tough to read and track multiple problems when they are mixed in one GitHub ticket. 

Please feel free to log a separate GitHub ticket for each query as it will help me and others to follow the conversations quickly.
