### ISSUE TITLE
it is not working properly

### ISSUE THREAD

**Issue by Jury1985** [datech/node-red-contrib-amazon-echo#56]
Hello, i have the problem with the update from Amazon, i have try to fix it with portforwarding over the iptables. from port 80 to 8080
My Problem is was is working only a time , than i can not search my devices or send him orders.

i use the echodot from first generation.
i use node red 0.20.5
i use node red on a Raspberry pi that is configured as an wlan access point i create an own Wlan for my smarthome devices. and the echodots are connectet to the home Wlan. 

i dont know how i must lock for the Problem, 

sorry for may bad english, i hope you can help me.

**Comment by datech** [comment]
Have you tried to run the Amazon Echo Hub on port 80?

**Comment by Barabba11** [comment]
If you are sure it worked one time check your network, is the Echo in the same IP subnet domain? Do you use another echo with the same Amazon account and that echo is under another network?
Try also to remove echo from your Amazon account, then reset it (search around how to reset echo 1, I can reset echo2 by pressing long a button (after remove from account)

**Comment by Jury1985** [comment]
Yes i have port 80 in use. 
my problem is solved.
the roblem was that i must reconnect my echodots. 
thanks for the support, normaly i never has think that this can be the problem.
