### ISSUE TITLE
Devices are discovered multiple times and no payload is sent

### ISSUE THREAD

**Issue by thmeger** [datech/node-red-contrib-amazon-echo#57]
##### SUMMARY

I get a payload object from the hub
`{"on":true,"bri":254,"hue":0,"sat":254,"ct":199,"colormode":"ct","rgb":[255,0,0],"payload":"on","deviceid":"7030cb49980414","topic":"","_msgid":"87726c7f.306df"}`

, but there is nothing in the debug node from the device node. The device node (keyword) has been found in Alexa device and is shown as 
"Deckenlampe
Royal Philips Electronics intelligentes Gerät"

So there are two problems. 
1) devices are found multiple times.
2) the hub sends information, but the device nodes do not. 

##### ECHO DEVICES

* Echo Dot 2nd generation
* Echo Plus 3rd generation 

##### MODULE VERSION

```paste below
0.1.8
```

##### CONFIGURATION

```paste below
[{"id":"1fc1aed.058dcd1","type":"link in","z":"315f7f75.d64738","name":"","links":["758ed315.72cb34"],"x":135,"y":160,"wires":[["af38e661.e6bde"]]},{"id":"af38e661.e6bde","type":"amazon-echo-device","z":"315f7f75.d64738","name":"Deckenlampe","topic":"","x":360,"y":160,"wires":[["a110883e.bf9518","50cdd64b.3fe69"]]},{"id":"50cdd64b.3fe69","type":"debug","z":"315f7f75.d64738","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":390,"y":260,"wires":[]},{"id":"1941dcc1.c6e833","type":"loxone-webservice","z":"315f7f75.d64738","name":"Deckenlampe an","miniserver":"4d42c899.423ef8","uri":"jdev/sps/io/LI-Deckenlampe/AI1/1001000100000","appendpayload":false,"x":930,"y":160,"wires":[[]]},{"id":"5c318f97.f35c88","type":"loxone-webservice","z":"315f7f75.d64738","name":"Deckenlampe aus","miniserver":"4d42c899.423ef8","uri":"jdev/sps/io/LI-Deckenlampe/changeTo/778","appendpayload":false,"x":930,"y":220,"wires":[[]]},{"id":"a110883e.bf9518","type":"switch","z":"315f7f75.d64738","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"on","vt":"str"},{"t":"eq","v":"off","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":3,"x":590,"y":220,"wires":[["1941dcc1.c6e833","23eea3d3.021f44"],["5c318f97.f35c88"],["23eea3d3.021f44"]]},{"id":"23eea3d3.021f44","type":"debug","z":"315f7f75.d64738","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":840,"y":340,"wires":[]},{"id":"4d42c899.423ef8","type":"loxone-miniserver","z":"","host":"192.168.178.77","port":"5066","enctype":"0","active":true}]
```

##### CONSOLE OUTPUT

```paste below

```
pi@raspberry:~ $ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:80
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by a-bailey** [comment]
Having the same problem, it works if I remove the duplicates by hand but thats not really an elegant solution if you have to do that everytime you rediscover the devices. I'm also looking into the code but can't really figure out why Alexa would do that

**Comment by a-bailey** [comment]
@datech theres only 1 hub in my flow, one thing I did was copy the nodes from the main to a dedicated alexa flow (deleted the original ones of course also cant find any other amazon hub by using the node-red search feature).
Also by calling *myIP/Port*0/api/c6260f982b43a226b5542b967f612ce/lights
returns the correct amount of devices and not double like alexa detects..

**Comment by datech** [comment]
Because the hub is relaying on node IDs, a copy will introduce an entirely new set of your devices with the same names. The solution is to delete the devices from Alexa and rerun the discovery procedure.

**Comment by a-bailey** [comment]
Thats what I was thinking, I forgot all devices multiple times but maybe I have to forget them and wait or bit or restart alexa or some rubbish.. I'll try that this evening thanks.

**Comment by thmeger** [comment]
Yeah, finally I reinstalled my pi and after that all worked again. There seems to be same caching of devices on the amazon side or whatever. Even after forget all device and deleting the nodes, the next find devices call found all the old non-existing device again. Anyhow, it works for now. :-)

**Comment by Barabba11** [comment]
There is maybe a bug between Amazon and echo, you remove devices but it doesn't tell echo to remove them. Try to reset your echo too, you need remove the echo from account, and keep press the config button, it should say it resets to factory default.
You need to register every echo to a different Amazon account, if you use one account only, only the master echo (the first you added) will send to hub in node red

**Comment by a-bailey** [comment]
Resetting the echo did the trick, now only the correct amount gets identified and everything works. Seems like alexa somehow caches devices so that was the problem. Thanks for the help.

**Comment by datech** [comment]
Thanks, all.
