### ISSUE TITLE
module has stopped working recently

### ISSUE THREAD

**Issue by ghvader** [datech/node-red-contrib-amazon-echo#58]
##### SUMMARY
recently stopped working

##### ECHO DEVICES
Echo Dot 1st generation

##### MODULE VERSION
```
0.1.8
```

##### CONFIGURATION
```
this isn't a configuration issue, other alexa modules have stopped working recently as well.
some type of change has taken place.
```

##### CONSOLE OUTPUT
```
this isn't a configuration issue, other alexa modules have stopped working recently as well.
some type of change has taken place.
```

##### STEPS TO REPRODUCE

this isn't a configuration issue, other alexa modules have stopped working recently as well.
some type of change has taken place.
##### EXPECTED RESULTS

this isn't a configuration issue, other alexa modules have stopped working recently as well.
some type of change has taken place.
##### ACTUAL RESULTS

this isn't a configuration issue, other alexa modules have stopped working recently as well.
some type of change has taken place.

**Comment by ghvader** [comment]
switching to a different module. this one appears to be abandoned.

**Comment by Barabba11** [comment]
pity to confirm that. Once the author replied some days ago,. but no developments coming. 
Did you find another one? Can you please report here which one? Thank you
