### ISSUE TITLE
Introduce of the "changed" attribute

### ISSUE THREAD

**Issue by datech** [datech/node-red-contrib-amazon-echo#64]
To be able to find what was changed in the device state, the output payload coming from the Amazon Echo Hub node will include a "changed" attribute. 

"changed" attribute is a hashmap of all changed attributes and the corresponding old values.

### Examples

**ON command**
```
{
   "on":true,
   "bri":254,
...
...
   "changed":{
      "on":false
   },
...
}
```

**Dim command**
```
{
   "on":true,
   "bri":100,
...
...
   "changed":{
      bri: 254
   },
...
}
```

**Comment by Barabba11** [comment]
Thank you, a lot
For me not really clear, the first case is it (?): I gave Alexa command on, and it was off before?
Second case: I tell Alexa dim 100, and it was 254?
In this way I've to make a function, store all the given values (but after restart I don't have them, trouble) and check for changes to understand the new command? Seems a bit complicated. Better the method of Verjus that give on payload the new command directly..

**Comment by datech** [comment]
#67 will be implemented instead
