### ISSUE TITLE
Devices recognized only from one particular Echo

### ISSUE THREAD

**Issue by Barabba11** [datech/node-red-contrib-amazon-echo#68]
Thank you for this important release, I'll test it when I'll back home. As I suppose you may still working on it I would suddenly ask if you introduced a filter, on the device node configuration html, to allow answer only to one particular Echo IP. I see you wrote the module outputs it now with other meta, but in my case this is not that useful. If I have "curtains" in 2 floors without filters both echos catch the same device, which is also duplicated, and telling one echo to close curtains will close both of each floor.
Thank you if I can introduce it, if the field is empty all IP can see that device, so nobody has to change nothing upgrading module, if they don't need to filter the source IP.
Or I may create a function between hub and device to filter out the unwelcome IP? But this function should be bidirectional?

**Comment by Barabba11** [comment]
I installed the 1.9 but I can't filter the device by IP. I have 2 echos in 2 different floors and I want to use the same name, for example curtains, I can't create 2 devices with the same name.. I can filter after by IP in a function and activate the proper curtain but both Echo will discover all devices of the other room, and I don't want that someone will play with the second echo to activate something on the other floor..

**Comment by datech** [comment]
I don't have plans to implement filtering, but I still want to include **#17 Enable/Disable of device nodes**, which will allow you to disable devices during discovery procedure

**Comment by Barabba11** [comment]
Unfortunately this is not a safe way, because it's necessary to tell (wrongly, forgetting i should not do it, and maybe not me but.my wife) Alexa to discover devices one day, for example to add my new phone Bluetooth, and the devices which were disabled/hidden will be discovered again.
Ok if you don't have this goal can I do it by functions? Can I put between every connection from hub to device a function and filter out the unwelcome ip?
Thank you for answer/support

**Comment by Barabba11** [comment]
@datech hi, may you please tell me if a function that will filter the incoming IP address between hub and device will stop Alexa discover device? Thank you a lot!

**Comment by datech** [comment]
Unfortunately, any Amazon Echo Device nodes added to the flow will be included in the dicovery process.

It is quite silly, but what I can suggest to you for now is: 

1. Delete the second-floor devices
2. Deploy
3. Ask Alexa to discover the devices
4. Undo the deletion
5. Delete the first-floor devices
6. Deploy
7. Discover
8. Undo

**Comment by Barabba11** [comment]
Thank you for answer, unfortunately there are 2 negative sides behind thatf I discover an then delete when I'll create them again there will be another id, and all devices discovered will be no more available. The second is if someone may just wrongly say Alexa discover.. it's already too late.
I see your script do not use wires for discover but it sees the devices already on flow, Meena it needs to be modified for that ((

**Comment by Barabba11** [comment]
Do you think can be easier modified if the other devices will be in another flow?

**Comment by datech** [comment]
Just checked, and hub will get all available devices in all flows.

Have you tried with undo, not recreate?

**Comment by Barabba11** [comment]
When I was writing it I was wolking fast to work, sorry for the mistakes. 
What you wrote has sense, new NR had the undo option.. I can have a try, but it worth only if I can after disable the device discovery in hub, so after the process Alexa can discover but it can't find new devices at all. DO you think it' s possibile to disable it?
Writing it, I think about it, and maybe I'm afraid blocking the discovery can cause Alexa malfunctions. Maybe Alexa will pretend sometime to know if the device exist and use the same procedure.. it might create problems

**Comment by datech** [comment]
I was thinking today also for an option that will disable the discovery procedure. It shouldn't be hard to implement and might work in your case.

**Comment by Barabba11** [comment]
thanks, 
I'm looking to your script, I think that here the script is telling Alexa the devices available:
pp.get('/api/:username', function(req, res) {
yes? in this case it may be enough to add a check if the req.connection.remoteAddress matches the one that will be defined in the device html.. I'll try to focus on it
