### ISSUE TITLE
Alexa cannot set to 1 w/o brightness word

### ISSUE THREAD

**Issue by crocri** [datech/node-red-contrib-amazon-echo#70]
##### SUMMARY

If I ask Alexa, "module name" to one, Alexa does not know how to do, but 
two to hundred works w/o any issues.
If I ask Alexa, set brightness of "node name" to one it's working too.

##### ECHO DEVICES

Echo Dot 1st generation
Echo Plus 2nd generation 
Echo Spot

##### MODULE VERSION

```paste below
0.1.9
```

##### CONFIGURATION

```paste below

```

##### CONSOLE OUTPUT

```paste below
n/a
```

##### STEPS TO REPRODUCE

Ask Alexa set to one - it's not working.
On German: Alexa, "name of the node" auf 1 -> failed
Alexa, "name of the node" auf 2 (or 3 to 100) -> worked
Alexa, setze Helligkeit von "name of the node" auf 1 -> worked too

##### EXPECTED RESULTS

Should work with "one" too
##### ACTUAL RESULTS

see above

**Comment by datech** [comment]
I don't have control over this, as Alexa is deciding what to send to the hub, but just tested on my Dot v3, and it works.
