### ISSUE TITLE
Enable change_direction attribute

### ISSUE THREAD

**Issue by PaulNBerlin** [datech/node-red-contrib-amazon-echo#73]
I also want to control my roller shutters / blinds using alexa.
To do this it is necessary that up/down/stop commands are transfered by this node to other nodes.

This "change direction" option seems to be not implemented for this node.
It is implemented and working for me in other nodes like "node-red-contrib-alexa-home" (but I prefer this node :-))
They did this to implement:

>     https://github.com/mabunixda/node-red-contrib-alexa-home/blob/master/alexa/alexa-home.js
>     // Detect increase/decrease command
>     msg.change_direction = 0;
>     if (msg.payload.bri) {
>       if (msg.payload.bri < node.bri) {
>         msg.change_direction = -1;
>       }
>       if (msg.payload.bri > node.bri) {
>         msg.change_direction = 1;
>       }
>     }

Is it possible to add something similar to your code?

Thanks

**Comment by Barabba11** [comment]
I would like to be optimistic too.. but this module is a clone of the Philips bulb, and as long Alexa will recognize it as a light she will just receive the commands suppose to be told to a light (not a shutter).
Fortunately in italian the words are similar, so it works as well

**Comment by Barabba11** [comment]
something similar was discussed here:
https://github.com/datech/node-red-contrib-amazon-echo/issues/34
and datech marked it as an enhancement.. so maybe he has something in mind that could make it possible. Maybe is possibile to clone other devices too..

PS: @datech there are news about 1.10? Will it support the disable discover of devices? Thank you a lot!

**Comment by PaulNBerlin** [comment]
Could solve the issue using node red (Maybe not the most elegant way but it is working :-)).
It now looks like this:

![Bild1](https://user-images.githubusercontent.com/56580878/66986417-2c0d4e00-f0bf-11e9-8f1d-451db479040d.png)

Only issue I still have is, that I need to "turn on" my blinds once initially when Alexa discovered them. After this one time activity everything works even when I turn them "off" - which will result in Stopping the blinds from moving (turning them on result in the same).
I can now say "Alexa blinds up; Alexa blinds down; As well as Alexa blinds on/off which results in stopping them. Telling Alexa to "stop" the blinds she is telling me that there is no device with name blinds. 
I cannot say Alexa put the blinds 50% Percent, But I dont need this.

Before I found the solution above I tried something like this (It also worked but looks much more complicated).

![Bild2](https://user-images.githubusercontent.com/56580878/66986604-84445000-f0bf-11e9-8011-1a2d9cda6930.png)

**Comment by datech** [comment]
@PaulNBerlin May we consider this as resolved and close it?

**Comment by datech** [comment]
Having the meta.changes in the output has to be enough to find the direction:

```
if (msg.meta.changes.bri) {
  if (msg.meta.changes.bri < msg.bri) {
    msg.change_direction = -1;
  }
  if (msg.meta.changes.bri > msg.bri) {
    msg.change_direction = 1;
  }
}
```

**Comment by PaulNBerlin** [comment]
Exactly!

**Comment by PaulNBerlin** [comment]
Is this a question?

**Comment by datech** [comment]
I'm trying to say that we have so many different cases where this module can be used, and it will be impossible to cover the specifics for each device. That's why I've added meta.input and meta.changes arrays. So, each of us can use the metadata arrays to create JS functions that can meet their specific requirements. 

That's why I don't think that we have to include change_direction in the output.

**Comment by PaulNBerlin** [comment]
Understand.
