### ISSUE TITLE
unable detect device

### ISSUE THREAD

**Issue by KengHzou** [datech/node-red-contrib-amazon-echo#75]
I have look around all the existing solution but still not working.
My 3rd gen echo dot is not able to detect the devices. 

Here is my Code
`[{"id":"87ed8a91.b80988","type":"amazon-echo-hub","z":"4ed1bad7.1b2c64","port":"80","processinput":"0","x":146.01303100585937,"y":324.99998474121093,"wires":[["826975f5.9db5e8"]]}]`

I have tried to debug on this few stuff.
1. same network.
2. able to ping my echo dot.
3. firewall is disabled.
4. nodered is running on admin

Environment
Wins 10
node-red v6+
node js v10+

**Comment by Barabba11** [comment]
you probably need to map the HUB port (should be bigger than 1023) to port 80. Look in troubleshooting to solve that

**Comment by samazw** [comment]
Remark for node-red running on raspberry pi:
Upgrading jessy seems to install lighttpd which then uses port 80. So uninstalling lighttpd using command "sudo apt-get remove lighttpd" and then starting node red as root "sudo node-red" will make this node working well again. 

Regards
Sascha Magold

**Comment by datech** [comment]
@KengHzou Have you managed to resolve it?
