### ISSUE TITLE
identify the Alexa device

### ISSUE THREAD

**Issue by mastercroc** [datech/node-red-contrib-amazon-echo#76]
Hello,

I'm trying to identify the Alexa device and the room where the command was given.
According to an earlier post this should be returned in this area in the JSON. 

> "meta": {
> 	"insert": {
> 		"by": "alexa",
> 		"details": {
> 			"ip": "::ffff:192.168.4.1",
> 			"user_agent": "Dalvik/2.1.0 (Linux; U; Android 5.1.1; AEOBC Build/LVY48F)",
> 			"date": "2019-10-22T03:39:24.613Z"
> 		}
> 	},
> 	"input": {
> 		"on": true
> 	},
> 	"changes": {
> 		"on": false
> 	}
> },

Unfortunately, I ALWAYS get the same information no matter from which device I start a command.

Did I misunderstand something or is this a bug?

**Comment by datech** [comment]
This is expected behavior. Only Alexa master device is communicating with the Amazon Echo Hub node.

That's why I wasn't a fan of providing such information in the output, as most of the cases, people will try to use the IP to identify which Echo device is sending the command, but unfortunately, all commands are sent my the master Alexa device. 

Here is what we have in the documentation:
> **meta.insert.details.ip** _string_
> Alexa master device IP address.
> Only if **meta.insert.by**=_alexa_

Let me know if you think that we have to update it somehow.

**Comment by Barabba11** [comment]
Create a new Amazon account, use the second account on the second Echo. Post here the result

**Comment by mastercroc** [comment]
thanks for the quick reply

I've got several Alexa all over my place and would like to identify the room where I’m sending the command.
This will give a lot of new ability’s in the flow.

I agree with you the master Alexa is not of any use.
The output is also made complex, for sure most of the user would like a simple output of the IP. 
I hope the community will agree to change this.

Thanks

**Comment by Barabba11** [comment]
Simple or not you have that output, it doesn't cost to make a function to read that as it is now.
The big question is if you want to use the same device names for every room, in this case you need to discover them separately. We're waiting the new release which hopefully will contain a trick to do that, we're discussing about it already

**Comment by mastercroc** [comment]
Hello Barabba,

thanks for your replay.
Yes, I want to identify the device and whit that the room.
To use a separate Amazon account for every devise could be an option (a bit painful counting the number of devices I have).
I’m hoping the team will add IP or the ID of the commanding Alexa to JSON send from the node.

If something else comes to your mind, please let me know.

regards

**Comment by datech** [comment]
Duplicate to #22

**Comment by Barabba11** [comment]
I suggest you to read this:
https://github.com/datech/node-red-contrib-amazon-echo/issues/68

**Comment by Barabba11** [comment]
> 
> 
> Hello Barabba,
> 
> thanks for your replay.
> Yes, I want to identify the device and whit that the room.
> To use a separate Amazon account for every devise could be an option (a bit painful counting the number of devices I have).
> I’m hoping the team will add IP or the ID of the commanding Alexa to JSON send from the node.
> 
> If something else comes to your mind, please let me know.
> 
> regards

There are no chance to distinguish different Echos if you use the same account. No chances. So use the painful way to create an account for each Echo
