### ISSUE TITLE
alexa responce "not quite sure what went wrong"

### ISSUE THREAD

**Issue by itishfrog** [datech/node-red-contrib-amazon-echo#77]
First thanks for your work in this worked perfectly on raspberry pi, now ive moved to ubuntu box it woks kinda, echo does what I ask but then I get a response of "not quite sure what went wrong"
if I look at the cell app it have a very short unresponsive message

I have Echo Dot 1st generation and Echo Plus 2nd generation both are doing this

I have not used port 8080 but rather 8000 and set ip tables according to trouble shooting 

Chain PREROUTING (policy ACCEPT 1 packets, 78 bytes)
 pkts bytes target     prot opt in     out     source               destination
    3   418 REDIRECT   tcp  --  ens32  any     anywhere             anywhere             tcp dpt:http redir ports 8000

Example of flow

[{"id":"de5bf844.c63778","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"acc4e9af.3d528","type":"link in","z":"de5bf844.c63778","name":"","links":["c8daabbd.d568b","a86928b5.5219a"],"x":295,"y":60,"wires":[["9830d5ba.856918"]]},{"id":"9830d5ba.856918","type":"amazon-echo-device","z":"de5bf844.c63778","name":"Study","topic":"Study","x":413,"y":60,"wires":[["5e13b78.40994c8"]]},{"id":"5e13b78.40994c8","type":"exec","z":"de5bf844.c63778","command":"/home/pi/.local/bin/yee --ip=192.168.0.7 turn","addpay":true,"append":"","useSpawn":"false","timer":"","oldrc":false,"name":"Study on off","x":850,"y":60,"wires":[[],[],[]]},{"id":"88918644.406a5","type":"amazon-echo-hub","z":"de5bf844.c63778","port":"8000","processinput":"2","x":410,"y":120,"wires":[["c8daabbd.d568b"]]},{"id":"c8daabbd.d568b","type":"link out","z":"de5bf844.c63778","name":"alexa","links":["acc4e9af.3d528","1450d26.06cef2e","73496364.d9d0ec","fd6e4d19.e2c56","dfdfb71d.536938","93a4b044.be599","6adca0f.f44fd6","4f901137.dc90c","1a4e8c55.d97364","b6640a65.276d88","8e7f9bd.feaca68","7512e7a7.4bb","ff3c2915.bb07a8","e16686a.4b43078","fc21e62f.f5ad58","e1448ee.026207"],"x":555,"y":120,"wires":[]}]

Any help would be appreciated

Tks

**Comment by tsprivate** [comment]
I have several Echo Doe Gen1 & 2 and having the same response as above.

The request is executed properly and debug shows all the correct parameters but Alexa keeps saying something went wrong !  ... Alexa is wrong ..lol

**Comment by Corundex** [comment]
I used the command 'sudo setcap 'cap_net_bind_service=+ep' /usr/bin/node' on Ubuntu to let the nodejs use port 80 under non-root user.
All works fine, but Alexa suspects something - keeps saying 'not quite sure what went wrong'.

**Comment by Corundex** [comment]
if it helps:
PUT /api/c6260f982b43a226b5542b967f612ce/lights/30e50c98d02574/state HTTP/1.1
Content-Type: application/json
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; AEOBC Build/LVY48F)
Host: 172.16.0.61
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 11

{"on":true}


HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 198
ETag: W/"c6-NNlK8CeL/Xjz6fZHi9PAkv6YkmY"
Date: Sun, 03 Nov 2019 00:12:57 GMT
Connection: keep-alive

[{"success":{"/lights/1/state/bri":254}},{"success":{"/lights/1/state/on":true}},{"success":{"/lights/1/state/hue":0}},{"success":{"/lights/1/state/sat":254}},{"success":{"/lights/1/state/ct":199}}]


GET /api/c6260f982b43a226b5542b967f612ce/lights/30e50c98d02574 HTTP/1.1
Content-Type: application/json
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; AEOBC Build/LVY48F)
Host: 172.16.0.61
Connection: Keep-Alive
Accept-Encoding: gzip

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 321
ETag: W/"141-2TIf27V+NSBSWdsYmthZ0EggCeQ"
Date: Sun, 03 Nov 2019 00:12:57 GMT
Connection: keep-alive

{"state":{"on":true,"bri":254,"hue":0,"sat":254,"effect":"none","xy":[0,0],"ct":199,"alert":"none","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"noupdates","lastinstall":"2019-11-03T00:12:57"},"type":"Color Temperature Light","name":"base","modelid":"LTW011","swversion":"1.29.0_r21169"}

**Comment by Corundex** [comment]
Actually I just fixed it - node was listening on both ethernet & wi-fi interfaces, I kept only ethernet and removed/added again the device in Alexa. All Alexa's suspicions are gone.

**Comment by itishfrog** [comment]
THANKS A MILLION !!!!!

i have 4 nic just ran 249241sudo ifconfig "nic" down on each of the unused ports and pesto

**Comment by itishfrog** [comment]
THANKS A MILLION !!!!!

i have 4 nic just ran sudo ifconfig "nic" down on each of the unused ports and pesto

**Comment by datech** [comment]
[Troubleshooting](../wiki/Troubleshooting) page has been updated:

#### Alexa: "I am not quite sure what went wrong"
Check that your Node-Red instance is not running on multiple network interfaces from the same network.
For example, your Node-Red may be listening on ethernet and WiFi interfaces.
