### ISSUE TITLE
Possible to run on RaspberryMatic + RedMatic?

### ISSUE THREAD

**Issue by renkei** [datech/node-red-contrib-amazon-echo#78]
I'm using Node-Red via RedMatic addon for RaspberryMatic. Port 80 is already in use by the webserver of RaspberryMatic. When I try to deploy a flow with the amazon echo hub it creates the error message (as expected):

"Error: listen EADDRINUSE: address already in use :::80"

I'm not a network expert, but I assume that it is not possible to configure the port forwarding like mentioned in the wiki, because then the RaspberryMatic webserver is no longer reachable on port 80. Or am I wrong?

Any idea?

**Comment by Barabba11** [comment]
Echo search devices on port 80, you can't change Echo. Maybe you can change the port of raspberry matic and access it with browser

**Comment by renkei** [comment]
Ok, I've solved this by changing the port of the lighttpd WebServer used by the RaspberryMatic WebUI. Now, it works.
