### ISSUE TITLE
Control paired Hue bulb from node red?

### ISSUE THREAD

**Issue by 877dev** [datech/node-red-contrib-amazon-echo#86]
Hi Teodor,

Thank you for the node, I have it working with node red container in local host mode.
I also have a flow working like your sonoff example, which dresses the Alexa app states.

My question is, I have a philips hue bulb paired to my Echo 3rd gen. Is there a way to control it via node red? I think the problem may be finding the device id of the hue bulb?

Thanks for any advice!

**Comment by E1cid** [comment]
try node-red-contrib-alexa-remote2

**Comment by datech** [comment]
@877dev, I'm afraid that it will not be possible if you don't have Philips Hue hub. All  Philips Hue bulbs paired to Alexa are utilizing the ZigBee or Bluetooth , so if you don't have a hardware hub you shouldn't be able to go on the IP (Node-Red) level

node-red-contrib-alexa-remote2 might be an option. @E1cid, have you tried such setup?

**Comment by E1cid** [comment]
yes i use alexaremote2 to turn on all devices connected to alexa. So if the hue lights are connect to alexa there node-red can control them.

i have sonoffs controlled un flashed
also tuya,magic home, smartlife, and my tosiba tv.

I don't use hue but i don't see why they can not work.
most devices work with smarthome straight out.
If that does not work add the alexa device via to a routine and then in alexaremote2 use routine to trigger

**Comment by datech** [comment]
Thanks for the feedback, @E1cid 

Another option could be to call the real Hue Bridge API if you used such to pair your bulbs.
