### ISSUE TITLE
on_off_command

### ISSUE THREAD

**Issue by micha910** [datech/node-red-contrib-amazon-echo#87]
##### SUMMARY
Hello,
thank you for your work on these very usefull software.
The controller works fine but I miss a distinction between the ON/OFF command and the dimming/brightness command.
It doesn`t matter what I say, _Alexa dim the light to 50%_ or _turn the light on/off_, the node will always send both:

**msg.payload "on"** and
**msg.bri "50"** 

So it can't really distinguish whether Alexa was told to on/off or just dim the light or whatever.
One command will always overridden. In the old alexa.local controller was the **msg.on_off_command** where you could distinguish. Would it be possible to implement the function with one of the next versions? 

##### ECHO DEVICES

* Echo Plus 2nd generation 

##### MODULE VERSION
0.1.9

**Comment by Barabba11** [comment]
Check the meta object and you will find the solution

**Comment by micha910** [comment]
I have overlooked that, thank you!
