### ISSUE TITLE
Unraid port 80 for alexa

### ISSUE THREAD

**Issue by kodatius** [datech/node-red-contrib-amazon-echo#88]
##### SUMMARY

Can't connect to alexa device port 80 in unraid. Any alternatives

##### MODULE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### CONSOLE OUTPUT

```paste below

```

**Comment by rlust** [comment]
Lookin for help on same issue.

**Comment by michaelschort** [comment]
ersiehst way would be to give the node-red Container an own ip Adress with br0 (there are Tutorials out there how to Set this up)

**Comment by datech** [comment]
@kodatius have you tried the resolution suggested by @michaelschort

**Comment by kodatius** [comment]
@datech I haven't been able to get it working, sadly. I'm Probably doing something wrong

**Comment by Barabba11** [comment]
If I remember correct there was another topic where we discussed it. The port 80 was in use, he found a way to free it

**Comment by datech** [comment]
@kodatius What do you see when you open http://{your-ip-address}:80/ ?

**Comment by isaga1234** [comment]
I use port 1080 (no problem with opening this port without privileges) and apache reverse proxy from port 80 to port 1080. It works

**Comment by bdydrp** [comment]
> I use port 1080 (no problem with opening this port without privileges) and apache reverse proxy from port 80 to port 1080. It works

Do you mind explaininv your reverse proxy?
I have nodered on unraid with its own IP on br0, but still cant get this to work
Thanks

**Comment by Barabba11** [comment]
There are many topics opened about it,you better search than wait.
There is also troubleshooting section made by author

**Comment by bdydrp** [comment]
Ive searched, but only thing i can find is i need to run nodered on host network
Mine are on br0
Even i set the port to 9000 in the alexa node, i cant get it to work

**Comment by Barabba11** [comment]
https://github.com/datech/node-red-contrib-amazon-echo/wiki/Troubleshooting

**Comment by bdydrp** [comment]
Thanks
Reading that, all new amazon devices need port 80 on host network
So having nodered on br0 docker network wont work, not with latest gen devices anyway

**Comment by isaga1234** [comment]
Maybe port 8000,8001, are a better choice, the question is the same. Configure one port for Alexa node red.
When asked, Alexa device will only look or discover port 80 and cannot find this 8000 or 1080 port.
Then IF you are not using port 80 for other purposes (in  my case I use only port 443 for a web server), you can setup a reverse proxy in Apache2. The reverse proxy will forward the requests to port 80 to your (8000 or 1080 or whatever). 
This will only happen provided you're not using port 80 before.
  -> netstat --tcp --listening --programs --numeric  (to verify if port 80 is occupied)
To create the reverse proxy you should look into apache or nginx documentation.
 cd to /etc/apache2/sites-enabled/ or sites-available
I added the following configuration

    <Location />
        ProxyPass http://192.168.xx.yy:1080/
        ProxyPassReverse http://192.168.xx.yy:1080/
        Order allow,deny
        Allow from all
    </Location>
change xx, yy and port 1080 to your configuration.
Also you can filter more in allow from all if needed

**Comment by bdydrp** [comment]
> Maybe port 8000,8001, are a better choice, the question is the same. Configure one port for Alexa node red.
> When asked, Alexa device will only look or discover port 80 and cannot find this 8000 or 1080 port.
> Then IF you are not using port 80 for other purposes (in my case I use only port 443 for a web server), you can setup a reverse proxy in Apache2. The reverse proxy will forward the requests to port 80 to your (8000 or 1080 or whatever).
> This will only happen provided you're not using port 80 before.
> -> netstat --tcp --listening --programs --numeric (to verify if port 80 is occupied)
> To create the reverse proxy you should look into apache or nginx documentation.
> cd to /etc/apache2/sites-enabled/ or sites-available
> I added the following configuration
> 
> ```
> <Location />
>     ProxyPass http://192.168.xx.yy:1080/
>     ProxyPassReverse http://192.168.xx.yy:1080/
>     Order allow,deny
>     Allow from all
> </Location>
> ```
> 
> change xx, yy and port 1080 to your configuration.
> Also you can filter more in allow from all if needed

I have already changed unraid webui away from 80
Using the netstat cmd, 80 is not shown in the list.
However, i do know that my Nginx proxy manager container is running in bridge mode, and is forwarding ports 80 and 443
That is the only thing with port 80
Ill Look into nginx proxy manager documentation, to add your configuration
Cheers

**Comment by Barabba11** [comment]
Why you love complicated things? You just need these few commands:

Example iptables commands to redirect the traffic to port 8080

sudo iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080

Example commands to save iptables settings

sudo /etc/init.d/iptables-persistent save
sudo /etc/init.d/iptables-persistent reload

Which are written in the troubleshooting section you read

**Comment by bdydrp** [comment]
Well i tried those commands in an unraid console window, but dont think its worked as i cant discover devices

Is this what the description.xml should look like?
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<root xmlns="urn:schemas-upnp-org:device-1-0">

<specVersion>

<major>1</major>

<minor>0</minor>

</specVersion>

<URLBase>http://192.168.1.18:8080/</URLBase>

<device>

<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>

<friendlyName>Philips hue (192.168.1.18)</friendlyName>

<manufacturer>Royal Philips Electronics</manufacturer>

<manufacturerURL>http://www.philips.com</manufacturerURL>

<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>

<modelName>Philips hue bridge 2012</modelName>

<modelNumber>1000000000000</modelNumber>

<modelURL>http://www.meethue.com</modelURL>

<serialNumber>93eadbeef13</serialNumber>

<UDN>uuid:00112233-4455-6677-8899-2393d2c5f0a76e</UDN>

<serviceList>

<service>

<serviceType>(null)</serviceType>

<serviceId>(null)</serviceId>

<controlURL>(null)</controlURL>

<eventSubURL>(null)</eventSubURL>

<SCPDURL>(null)</SCPDURL>

</service>

</serviceList>

<presentationURL>index.html</presentationURL>

<iconList>

<icon>

<mimetype>image/png</mimetype>

<height>48</height>

<width>48</width>

<depth>24</depth>

<url>hue_logo_0.png</url>

</icon>

<icon>

<mimetype>image/png</mimetype>

<height>120</height>

<width>120</width>

<depth>24</depth>

<url>hue_logo_3.png</url>

</icon>

</iconList>

</device>

</root>

**Comment by Barabba11** [comment]
when you do your experiments keep in mind that:
1) Alexa will communicate with module only if it listen to port 80 (try with an external computer if it is opened in your device IP)
2) the NAT you're doing should be on the port where the module is listening.

I'm not going to support here more, good luck

**Comment by bdydrp** [comment]
Thanks - will keep it in mind
Thanks for your thus far - appreciate it

**Comment by isaga1234** [comment]
@Barabba11 
This is a good aproach also. I didn't remember it.
