### ISSUE TITLE
No devices found with Echo 2 and Echo Dot 3

### ISSUE THREAD

**Issue by nike12354** [datech/node-red-contrib-amazon-echo#9]
Hi all together,

I'm currently trying to dicover devices using the Amazon echo hub node. Heres my flow:
![grafik](https://user-images.githubusercontent.com/46595841/51791754-f2e72380-21a7-11e9-9634-c5fe52bd19b3.png)
The hub has the following config:
![grafik](https://user-images.githubusercontent.com/46595841/51791761-05f9f380-21a8-11e9-9386-21cb3fc60305.png)

Port 80 is open:
![grafik](https://user-images.githubusercontent.com/46595841/51791764-1611d300-21a8-11e9-9644-eb34384591cb.png)

No firewall is in place. Node-Red runs on Centos 7 via ioBroker as root. SELinux is disabled.
Telnet to port 80 from another device is successful.

Alexa app tells there are no new devices found. Any ideas?

Thanks in advance!

**Comment by datech** [comment]
Hello,

Can you confirm the following:
- you can access http://<your-node-red>:80/api/1028d66426293e821ecfd9ef1a0731df/lights
- Echo device and Node-Red machine are connected to one and the same network
- if docker container is used to run the Node-Red, it is configured to use host network. Otherwise, Amazon Echo Hub node will not be discovered
- the multicast traffic is not filtered

**Comment by nike12354** [comment]
Hi datech,

thanks for your response!

Here the results:
![grafik](https://user-images.githubusercontent.com/46595841/51792622-fed8e280-21b3-11e9-8db4-2455535da7eb.png)

- URL is accessible.

- All devices are within the same VLAN and subnet

- No Docker is in place

- as there is no firewall in place (it is disabled and service does not run) I have no idea what should block any multicast traffic. 

Further information: Node-Red runs on a virtual machine on VMware ESXi 6.7, which is connected to a trunk port on a L3-switch. Any other service running on this particular machine is fully accessible from my network. No routing is (because of the trunking) in place.

**Comment by datech** [comment]
Looks like the SSDP multicast traffic is not routed to the virtual machine.

I’ve just found this:
**Enable Multicast Snooping on a vSphere Distributed Switch**
https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.networking.doc/GUID-50AF72D4-F766-4D68-8330-BA15250E4E99.html

**Comment by nike12354** [comment]
This only applies to Virtual distributed switches using a vSphere vCenter. I already checked this. 
The vSwitch (not distributed) i use has no multicast filtering enabled, I already checked this.

Nevertheless thank you :)! Do you have any other ideas?

**Comment by nike12354** [comment]
What about the working node-red Wemo emulator - isn't it using SSDP as well? Only for diagnosis of the problem.

**Comment by datech** [comment]
I see, just ESX without vCenter.

Yep, Wemo emulator is using SSDP.

You may try to sniff the SSDP traffic. It has to be:
Src: <ECHO DEVICE IP>, Dst: 239.255.255.250
Src: <NODE-RED IP>, Dst: 239.255.255.250

**Comment by nike12354** [comment]
Okay I will install wireshark in a few minutes.

But I think this may be the wrong direction because SSDP works with the wemo. 

I'll reply in a few minutes

**Comment by nike12354** [comment]
I did various sniffs - Alexa sends various SSDP packages, but my server does not reply.
Just to be sure i deployed a Wemo node on the same server - now it answers visbly in wireshark, but only for the wemo.

**Comment by datech** [comment]
I'm using "peer-ssdp" module to implement the discovery procedure. The library is responding with packages which are not recognize as SSDP by Wireshark. So, if you use Wireshark the packages will be marked just as UDP. 
Wemo emulator is using "node-ssdp" module and it seems that it is responding with correct SSDP packages. 

Anyway, can you try to sniff the traffic on the Node-Red machine with tcpdump:
```
sudo tcpdump -i <your-network-interface> udp and dst <echo-device-ip> -vv -X
```

The package we are looking for is similar to this one:
```
.....:.P./..HTTP
/1.1.200.OK..HOS
T:.239.255.255.2
50:1900..CACHE-C
ONTROL:.max-age=
100..EXT:...LOCA
TION:.http://XXX
.XXX.XXX.XXX:80/d
escription.xml..
SERVER:.Linux/3.
14.0.UPnP/1.0.Ip
Bridge/1.17.0..S
T:.urn:schemas-u
pnp-org:device:b
asic:1..USN:.uui
d:00112233-4455-
6677-8899-..DATE
:.Sun,.27.Jan.20
19.00:12:44.GMT.
```

**Comment by nike12354** [comment]
Hey datech,

Thank you again! I will check this soon :).

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by nike12354** [comment]
Good morning,

I can report some success. Now I can see ssdp traffic after starting a new discovery with the new version:
![grafik](https://user-images.githubusercontent.com/46595841/51819404-8d438600-22d2-11e9-8740-a621a5bbc34f.png)

Unfortunately Alexa does not show any new devices :-/ 
I opened the URL stated in the trace:
![grafik](https://user-images.githubusercontent.com/46595841/51819472-c3810580-22d2-11e9-8462-e7e13a69da71.png)

Is there anything wrong?


I took the trace on a tablet in the same WiFi at the same access point where one of my Echo devices resides.

**Comment by datech** [comment]
Good morning,

Do you see any HTTP traffic from Echo to Node-Red? Echo device will try to open this URL and it has to be recored by Wirewark.

**Comment by nike12354** [comment]
Nope, no http traffic

**Comment by nike12354** [comment]
Just to be sure I initiated a full reboot of the whole infrastructure here at my place... Maybe it is just a faulting network stack of any device...
If there is still no success, I will deploy a VM on the same vSwitch as my node-red instance and sniff the traffic from there. But I have to do this later :D

**Comment by nike12354** [comment]
Still no hhtp traffic after full restart

**Comment by nike12354** [comment]
Update: the fifth discovery was successful. I actually don't know what changed in this time, but now It works

**Comment by datech** [comment]
I think that you don't see the HTTP packages, because the traffic is not routed through the Wireshark machine. You can see the SSDP packages as they are multicast and will be received by all network hosts.

Can you confirm that, now you can turn on/off the devices? Some users reported that they cannot set the brightness with Echo Dot 2nd gen. Is it working on your setup?

**Comment by nike12354** [comment]
Yes everything is turning off an on with dimming like a charm!

Of course you have to translate On and off commonly to true / false in the payload or use the msg.on msg.bri properties of the object by creating a new object with the respective payload.

Thank you datech! You helped me a lot :)

**Comment by nike12354** [comment]
Furthermore I cannot test the color of the light because I don't have the right bulbs for this...

**Comment by datech** [comment]
I’m glad that it is working now. 

Light devices are simulated, so the color mode have to be available in the Alexa app. Here is how it is looking on my setup with Echo Dot 3rd gen:

<img width="400" alt="node-red amazon echo alexa" src="https://user-images.githubusercontent.com/535026/51860845-59547900-2343-11e9-80f6-dfad1a01397a.jpg">

**Comment by nike12354** [comment]
Yeah the color Mode is available in the App. If it ist interestant for you, i can deploy a debug node and Check the Message when changing the Mode. From my Point of View the issue is resolved.

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by datech** [comment]
Thanks, I will close it.
