### ISSUE TITLE
Only one device detected with logitech harmony hub

### ISSUE THREAD

**Issue by nicinuse** [datech/node-red-contrib-amazon-echo#95]
##### SUMMARY
Hi there, 
I am using this node and it is working quite well with my echo dot 2nd gen. I would like to use the same emulated bridge with a logitech harmony hub, as it's detecting the bridge quite well. Sadly only one configured light/bulb device is detected. 
I wonder if it is possible to use this bridge with a logitech hub and multiple attached devices. 

##### ECHO DEVICES
* Echo Plus 2nd generation 

##### MODULE VERSION
```
0.1.9
```

**Comment by raufis27** [comment]
I have the same problem. Please, if possible, implement this feature.

**Comment by datech** [comment]
Can someone confirm that Logitech Harmony Hub is working with real hardware Philips Hue Bridge v1 and multiple devices linked to it?

**Comment by rogerroger-coder** [comment]
I had it running with Openhab 2.4 Hue Emulation (2.5 doesn't work at all)
It was running with 4 davices linked and mapped to buttons.

I'll check if it works with me current hue. Give me some minutes :)

**Comment by rogerroger-coder** [comment]
It does work with lights, groups of lights and scenes. Would it help if provide the discovery json of the original hue ? (Would need to check if its safe to share)

**Comment by datech** [comment]
I'm just guessing, but it might be because the current implementation is not using a different uniqueid for each device.

So, "uniqueid": "00:11:22:33:44:55:66:77-88" has to be changed to dynamically generated value. I can make the change for the next release, but I will not be able to test it.

**Comment by rogerroger-coder** [comment]
Sounds fitting, very nice.
I would happily test it for you!

But i would need a short guide how to patch node-red. 

And maybe what to test?

Existing nodes, new nodes, restarts , all functions from harmony hub (on, off, dimm+, dimm-)

**Comment by datech** [comment]
Can you test it with v0.1.10?

**Comment by rogerroger-coder** [comment]
Ah wow, this was fast. Will test it this evening :)

**Comment by nicinuse** [comment]
Hi there,
working fine for me now. All devices are found an can be controlled.
Thanks!

**Comment by rogerroger-coder** [comment]
Same here :) All fine great work!
