### ISSUE TITLE
Unterscheidung zwischen Szenen und Geräten

### ISSUE THREAD

**Issue by Nuggelbeb** [datech/node-red-contrib-amazon-echo#96]
Hallo,
kann man bei Node Red eine Einstellung vornehmen, welche bei der "Alexa Gerätesuche" eine Unterscheidung zwischen Szenen und Geräten macht?

**Comment by datech** [comment]
Currently, scenes are not supported by this module. #85 is the feature request about scenes that might be implemented in the future.
