### ISSUE TITLE
'Device' Doesnt support that..

### ISSUE THREAD

**Issue by Levynger** [datech/node-red-contrib-amazon-echo#97]
I get many "Device" Doesnt support that responses from Alexa.
the deiscovery works wekk onport 80.
however when i try to activate "Turn 'DeviceName' On" or "Turn On 'DeviceName'" i getting mosty response from alexa 
Device Doesnt Support That.

using Echo 3rd Gen
```
version 0.1.9
```

**Comment by datech** [comment]
@Levynger, did you mange to resolve this?

**Comment by bobneubaum-personal** [comment]
I have the same issue.  Tried changing output to on & payload with no luck... trying.  

running in v1.0.4 and running v 0.1.8 of the node

**Comment by datech** [comment]
Have you tried to update your Echo firmware?

**Comment by datech** [comment]
@bobneubaum-personal , @Levynger Do you have any update on this issue? Is it still reproducible?
