### ISSUE TITLE
Devices "not responding"

### ISSUE THREAD

**Issue by qeggs** [datech/node-red-contrib-amazon-echo#99]
##### SUMMARY
Echo says "device not responding" after moving device node to another tab in node-red. 
Also Echo continues to discover devices after they're deleted from node-red.

##### ECHO DEVICES
* Echo Dot 3rd Gen
* Fire TV Stick 4k
* Alexa app on Android

##### MODULE VERSION
```
v0.1.9 from within Hass.io (Home Assistant)
```

##### CONFIGURATION
```
[
    {
        "id": "ab74f973.b7c5b8",
        "type": "debug",
        "z": "da563dea.88676",
        "name": "debug A",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 460,
        "y": 200,
        "wires": []
    },
    {
        "id": "4dc7f5e6.717c4c",
        "type": "amazon-echo-hub",
        "z": "da563dea.88676",
        "port": "80",
        "processinput": 0,
        "x": 130,
        "y": 200,
        "wires": [
            [
                "bac78c2f.89eaa"
            ]
        ]
    },
    {
        "id": "bac78c2f.89eaa",
        "type": "amazon-echo-device",
        "z": "da563dea.88676",
        "name": "test",
        "topic": "",
        "x": 305,
        "y": 200,
        "wires": [
            [
                "ab74f973.b7c5b8"
            ]
        ]
    }
]
```

##### CONSOLE OUTPUT
```
Log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... -----------------------------------------------------------  Hass.io Add-on: Node-RED  Flow-based programming for the Internet of Things  -----------------------------------------------------------  Add-on version: 6.0.3  There is an update available for this add-on!  Latest add-on version: 6.0.4  Please consider upgrading as soon as possible.  System: HassOS 3.8  (armv7 / raspberrypi3)  Home Assistant version: 0.104.3  Supervisor version: 199  -----------------------------------------------------------  Please, share the above information when looking for help  or support in, e.g., GitHub, forums or the Discord chat.  ----------------------------------------------------------- [cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
audited 175 packages in 3.866s
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:51:14] INFO: Starting Node-RED... > hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
9 Feb 11:51:18 - [info] 
Welcome to Node-RED
===================
9 Feb 11:51:18 - [info] Node-RED version: v1.0.3
9 Feb 11:51:18 - [info] Node.js  version: v12.14.0
9 Feb 11:51:18 - [info] Linux 4.19.93-v7 arm LE
9 Feb 11:51:19 - [info] Loading palette nodes
9 Feb 11:51:26 - [info] Dashboard version 2.19.3 started at /endpoint/ui
9 Feb 11:51:28 - [info] Settings file  : /etc/node-red/config.js
9 Feb 11:51:28 - [info] Context store  : 'default' [module=memory]
9 Feb 11:51:28 - [info] User directory : /config/node-red/
9 Feb 11:51:28 - [warn] Projects disabled : editorTheme.projects.enabled=false
9 Feb 11:51:28 - [info] Flows file     : /config/node-red/flows.json
9 Feb 11:51:28 - [info] Server now running at http://127.0.0.1:46836/
9 Feb 11:51:28 - [info] Starting flows
[11:51:28] INFO: Starting NGinx... nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
9 Feb 11:51:29 - [info] Started flows
9 Feb 11:51:29 - [info] [server:Home Assistant] WebSocket Connecting http://hassio/homeassistant
9 Feb 11:51:29 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
[09/Feb/2020:11:51:34 -0500] 200 -(192.168.0.107) GET /endpoint/ui/socket.io/?EIO=3&transport=polling&t=N0gtGqS HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
[09/Feb/2020:11:51:34 -0500] 200 -(192.168.0.107) GET /endpoint/ui/socket.io/?EIO=3&transport=polling&t=N0gtGsV&sid=SdozZichSliq-LbrAAAA HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
```

##### STEPS TO REPRODUCE
1. Set up a device with hub Hub and device nodes. Device is labelled named "test".
2. Add debug node to read output of "test" device.
3. Confirm that the debug node properly receives data when issue a command to the "test" device via Alexa.
4. Cut and paste the hub, device and debug nodes to another tab in node-red and re-deploy the node-red workspace.
5. Issue "turn test off" to Alexa. In my case Alexa responds with "test is not responding".
6. Restart node-red completely as a troubleshooting measure.
7. Again, issue "turn test off" to Alexa. Again, in my case Alexa responds with "test is not responding".
8. Using alexa.amazon.com, have Alexa forget all smarthome devices.
9. Have alexa discover devices again. In my cases, Alexa also discovers old devices which have been deleted from my node-red workspace.
10. Restart node-red (this may be unnecessary, but just in case it helps).
11.  Again, issue "turn test off" to Alexa. Again, in my case Alexa responds with "test is not responding".

##### EXPECTED RESULTS
* Echo should output a message to debug node when commanding "test on".
* Echo should not discover old devices after they've been deleted from node-red.

##### ACTUAL RESULTS
* Echo says "test is not responding" when commanding "test" on or off.
* Echo continues to discover devices after they are deleted from node-red. This happens even after restarting node-red and waiting hours.

**Comment by Barabba11** [comment]
Hi, the reason is very easy, and it's the same why we can't backup our flow and restore it without reset and discover again all devices with Alexa; When you create a device NR will assign it a node id, this is sent to Alexa.. not the device name only, and this will be considered the real and unique name. If u change flow there will be others id.
It will be super if one day we can edit this id in the node properties, so we can also backup it

**Comment by qeggs** [comment]
Thank you for responding. Can you recommend a workaround? I am still getting "device is not responding" even after forgetting and rediscovering devices with Alexa.

**Comment by Barabba11** [comment]
Be sure you recreate the right flow, access Alexa Amazon account, remove Alexa, then reset Alexa by its buttons (find in YouTube how to),add it again and discover. If still not working maybe there is a problem with copying

**Comment by qeggs** [comment]
Solved! 

I factory reset my Echo by holding the action button down for 25 sections, then set it up from scratch and had it discover devices again. The device discovery worked as expected and "Alexa, turn test off" sent a message through to node-red as expected. 

Thank you!
